import React, { createContext, useCallback, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'zh';

interface Translations {
    [key: string]: {
        [key: string]: string;
    };
}

// Translations dictionary
const translations: Translations = {
    en: {
        'sidebar.navigation': 'Workspace navigation',
        'sidebar.open': 'Open sidebar',
        'sidebar.close': 'Close sidebar',
        'sidebar.newTask': 'New Task',
        'sidebar.currentTask': 'Current Task',
        'sidebar.chat': 'Chat',
        'sidebar.knowledge': 'Knowledge',
        'sidebar.plugins': 'Plugins',
        'sidebar.metrics': 'Metrics',
        'sidebar.settings': 'Settings',
        'sidebar.langToggle': 'Switch to Chinese',
        'sidebar.semantic': 'Semantic model',
        'sidebar.language': 'Language',
        'sidebar.logout': 'Sign out',

        'accessibility.skipToContent': 'Skip to main content',
        'common.loading': 'Loading…',
        'common.close': 'Close',
        'common.edit': 'Edit',
        'common.save': 'Save',
        'common.delete': 'Delete',
        'common.choose': 'Choose',
        'common.retry': 'Try again',
        'common.hostManaged': 'Host managed by Data Agent',
        'common.noKnowledgeFiles': 'No knowledge files yet.',
         'common.noKnowledgeFilesHint': 'Use New / Import above, or drop files into the knowledge folder in the data directory.',
        'common.knowledgeNew': 'New',
        'common.knowledgeImport': 'Import',
        'common.knowledgeImported': 'Imported',
        'common.knowledgeBuiltin': 'Built-in',
        'common.knowledgeBuiltinHint': 'Ships with the app and updates with it; read-only.',
        'common.knowledgePlaceholder': 'Empty',
        'common.knowledgePlaceholderHint': 'Placeholder: fill in this document so the Agent can use it.',
        'common.knowledgeNamePrompt': 'File name (e.g. doc/notes.md):',
        'common.noSemanticAssetsHint': 'Scanning the semantic project directory automatically; use refresh to re-scan.',
        'common.semanticRefresh': 'Refresh', 
        'common.noSemanticAssets': 'No semantic assets available.',
        'common.requestFailed': 'Request failed.',
        'common.retryHint': 'Check your connection or configuration and try again.',

        'app.preparing': 'Preparing Data Agent...',
        'app.startupError': 'Data Agent could not initialize its local runtime. Check the configuration and try again.',
        'app.retry': 'Try again',
        'desktop.file': 'File',
        'desktop.edit': 'Edit',
        'desktop.view': 'View',
        'desktop.window': 'Window',
        'desktop.help': 'Help',
        'desktop.menu': 'Application menu',

        'auth.registerSubtitle': 'Create the first admin account',
        'auth.loginSubtitle': 'Sign in to continue',
        'auth.username': 'Username',
        'auth.password': 'Password',
        'auth.createAccount': 'Create account',
        'auth.signIn': 'Sign in',
        'auth.submitting': 'Please wait',
        'auth.useExisting': 'Use an existing account',
        'auth.createFirst': 'Create first account',
        'auth.errorFallback': 'Authentication failed',

        'landing.nav.label': 'Landing navigation',
        'landing.nav.who': 'Who it\'s for',
        'landing.nav.what': 'What it does',
        'landing.nav.where': 'Anywhere',
        'landing.nav.build': 'How it\'s built',
        'landing.nav.why': 'Why yourDB',
        'landing.nav.how': 'How to use',
        'landing.enterApp': 'Open app',
        'landing.hero.eyebrow': 'An AI agent built for data work',
        'landing.hero.subtitle': 'Query, export, write the report, build the dashboard, all from one sentence. On your computer, in the browser or on your phone.',
        'landing.hero.primary': 'Start with yourDB',
        'landing.hero.secondary': 'Is it for me?',
        'landing.hero.platforms': 'Available on',
        'landing.demo.label': 'Product demo: from a fresh yourDB workspace, one request to the delivery_center database turns into a delivery snapshot dashboard',
        'landing.demo.play': 'Play demo',
        'landing.demo.pause': 'Pause demo',
        'landing.demo.chapters': 'Demo chapters',
        'landing.demo.ch.new': 'New task',
        'landing.demo.ch.ask': 'Ask',
        'landing.demo.ch.explore': 'Explore',
        'landing.demo.ch.query': 'Query',
        'landing.demo.ch.dashboard': 'Dashboard',
        'landing.demo.task1': 'Fulfillment review',
        'landing.demo.task2': 'Regional weekly sales',
        'landing.demo.question': 'Build a delivery snapshot dashboard from the delivery_center database.',
        'landing.demo.reasoning': 'Map tables and row counts first, then pin down a definition for every view.',
        'landing.demo.reasoningDone': 'Reasoning',
        'landing.demo.m1': 'Reading the method notes and sending explorers out in parallel.',
        'landing.demo.m2': "orders has 0 rows, so a monthly trend can't be computed, and I won't swap in an overall share. Building the snapshot from deliveries and payments.",
        'landing.demo.m3': 'Dashboard generated.',
        'landing.demo.file': 'Dashboard file',
        'landing.demo.dash.title': 'delivery_center delivery snapshot',
        'landing.demo.dash.chip1': 'Deliveries 378,843',
        'landing.demo.dash.chip2': 'Payments 400,834',
        'landing.demo.dash.chip3': 'Full snapshot',
        'landing.demo.dash.asof': 'Snapshot · 2026-10-02',
        'landing.demo.dash.summary': 'Key findings',
        'landing.demo.dash.f1': 'of deliveries are DELIVERED; statuses are concentrated and exceptions are rare',
        'landing.demo.dash.f2': 'of deliveries travel 1–3 km; plan capacity for short trips first',
        'landing.demo.dash.f3': 'of payments are ONLINE; the payment channel is highly concentrated',
        'landing.demo.dash.status': 'Delivery status',
        'landing.demo.dash.delivered': 'Delivered',
        'landing.demo.dash.cancelled': 'Cancelled',
        'landing.demo.dash.delivering': 'Delivering',
        'landing.demo.dash.unit': 'deliveries',
        'landing.demo.dash.share': 'Share',
        'landing.demo.dash.distTitle': 'Most deliveries travel 1–3 km (48.92%)',
        'landing.demo.dash.distSub': '378,770 deliveries with a distance · labels show share',
        'landing.demo.dash.donutTitle': 'Status mix: 98.03% delivered',
        'landing.demo.dash.donutSub': 'All 378,843 deliveries',
        'landing.demo.dash.payTitle': 'Payments concentrate on ONLINE (77.93%)',
        'landing.demo.dash.paySub': 'All 400,834 payments · labels show share',
        'landing.who.kicker': 'Who it\'s for',
        'landing.who.title': 'If one of these sounds like you, try yourDB.',
        'landing.who.desc': 'yourDB is an agent built for data work. It takes the everyday data requests off people\'s plates.',
        'landing.who.ops.name': 'The quiet ops person who hates bothering the data team',
        'landing.who.ops.pain': 'I need a number, but I\'ve already asked the data engineers twice this week.',
        'landing.who.ops.fix': 'Ask yourDB directly. No queue, no small talk.',
        'landing.who.ops.ask': 'What was last week\'s new-customer conversion rate?',
        'landing.who.engineer.name': 'The data engineer interrupted from every direction',
        'landing.who.engineer.pain': 'Ten ad-hoc pulls a day, and the real work keeps getting pushed back.',
        'landing.who.engineer.fix': 'Hand routine pulls to yourDB; it follows the definitions in your knowledge base.',
        'landing.who.engineer.ask': 'Export September GMV by channel as CSV',
        'landing.who.analyst.name': 'The analyst buried under parallel tasks',
        'landing.who.analyst.pain': 'Queries, tables, a report and a dashboard, all due today.',
        'landing.who.analyst.fix': 'One sentence gets the report and dashboard drafted. You check and decide.',
        'landing.who.analyst.ask': 'Write a Q3 business review for the East region',
        'landing.who.boss.name': 'The executive who wants numbers on demand',
        'landing.who.boss.pain': 'I\'m on the road and want to know how business is going today.',
        'landing.who.boss.fix': 'Ask from your phone and get the dashboard back in the chat.',
        'landing.who.boss.ask': 'Rank today\'s sales by store',
        'landing.what.kicker': 'What it does',
        'landing.what.title': 'Queries, exports, reports and dashboards.',
        'landing.what.desc': 'Four kinds of everyday data work, each started with one sentence.',
        'landing.cap.try': 'Try asking',
        'landing.cap.gets': 'You get',
        'landing.cap.query.title': 'Everyday queries',
        'landing.cap.query.desc': 'Ask in plain language. yourDB writes read-only SQL by your definitions, runs it, and shows you the query and the result.',
        'landing.cap.query.ask': 'Sales by region since September',
        'landing.cap.query.output': 'The answer, its SQL, and the result table',
        'landing.cap.query.prompt': 'Sales by region since September',
        'landing.cap.export.title': 'Data exports',
        'landing.cap.export.desc': 'Full verified results as CSV, ready for Excel or anything downstream.',
        'landing.cap.export.ask': 'Export all September orders as CSV',
        'landing.cap.export.output': 'A complete CSV file',
        'landing.cap.report.title': 'Analysis reports',
        'landing.cap.report.desc': 'Summary, data overview, key findings, charts and suggestions, in a structured Markdown report.',
        'landing.cap.report.ask': 'Write a Q3 business review for the East region',
        'landing.cap.report.output': 'A Markdown report with charts',
        'landing.cap.report.docTitle': 'East region · Q3 business review',
        'landing.cap.report.summary': 'Summary',
        'landing.cap.report.summaryText': 'Q3 sales reached 12.84M, up 6.2% on Q2, led by electronics.',
        'landing.cap.report.findings': 'Key findings',
        'landing.cap.report.f1': 'Electronics grew 11.4%, the fastest of any category.',
        'landing.cap.report.f2': 'Orders over 3 days late got twice as many bad reviews.',
        'landing.cap.dashboard.title': 'Analysis dashboards',
        'landing.cap.dashboard.desc': 'Production-grade standalone HTML dashboards. Every view comes from a verified, published result.',
        'landing.cap.dashboard.ask': 'Build a delivery snapshot dashboard from the delivery_center database',
        'landing.cap.dashboard.output': 'A single HTML dashboard file',
        'landing.dash.delivery.name': 'Delivery snapshot',
        'landing.dash.delivery.alt': 'Delivery data overview dashboard built on the Delivery Center dataset',
        'landing.dash.delivery.note': 'Real output · Delivery Center public dataset',
        'landing.where.kicker': 'Anywhere',
        'landing.where.title': 'Computer, browser, phone: one yourDB.',
        'landing.where.desc': 'A request comes in just after you leave your desk? No problem. Open your phone and get it done.',
        'landing.where.sync': 'Desktop, web and mobile stay in sync',
        'landing.where.desktop': 'Desktop',
        'landing.where.web': 'Web',
        'landing.where.mobile': 'Mobile',
        'landing.where.point.dashboard': 'Dashboards arrive as an image, with the HTML page attached',
        'landing.where.point.clarify': 'When a question is ambiguous, it asks you right in the chat',
        'landing.where.point.new': 'Send /new to start over; a long pause starts a fresh conversation',
        'landing.where.point.access': 'Only linked accounts, or people a member approves, can use it',
        'landing.phone.label': 'A conversation with yourDB on a phone',
        'landing.phone.status': 'online',
        'landing.phone.q1': 'How did East region sales do this week?',
        'landing.phone.a1': 'East region sales this week: 12.84M, up 6.2% on last week. Dashboard below.',
        'landing.phone.chartTitle': 'East region · weekly sales',
        'landing.phone.q2': 'Which category grew the most?',
        'landing.phone.a2': 'Electronics, up 11.4%. Want it broken down by city?',
        'landing.phone.input': 'Message yourDB',
        'landing.build.kicker': 'How it\'s built',
        'landing.build.title': 'From entry point to database, each layer has one job.',
        'landing.build.desc': 'Every entry point reaches the same runtime. Knowledge and skills are read on demand, answers go through the Answering module, and the database is only ever reached through MCP.',
        'landing.why.kicker': 'Why yourDB',
        'landing.why.title': 'Accurate, secure, effortless.',
        'landing.why.desc': 'Three promises, each backed by a concrete mechanism.',
        'landing.why.accurate.title': 'Accurate',
        'landing.why.accurate.desc': 'An answer is checked against what you asked before it reaches you. If it cannot be settled, yourDB asks you or says so.',
        'landing.why.secure.title': 'Secure',
        'landing.why.secure.desc': 'The agent never touches your database directly, and nothing it runs can change your data.',
        'landing.why.easy.title': 'Effortless',
        'landing.why.easy.desc': 'Charts, data pulls, dashboards and analysis from one sentence, on any device, in the format you need.',
        'landing.acc.answer.title': 'Answer module',
        'landing.acc.answer.desc': 'Your question becomes a versioned Answer Spec: hard constraints backed by evidence, hypotheses to verify, and open choices. The SQL is checked against it before any result is published.',
        'landing.acc.hypothesis.title': 'Hypothesis testing',
        'landing.acc.hypothesis.desc': 'Every interpretation the model infers is recorded as a hypothesis and must be supported or refuted with admitted evidence before it counts.',
        'landing.acc.loop.title': 'Dual-loop verification',
        'landing.acc.loop.desc': 'The outer loop settles what to answer; the inner loop settles how. A failed implementation does not change the definition, and a changed definition sends the implementation back for review.',
        'landing.acc.jev.title': 'Jev decision engine',
        'landing.acc.jev.desc': 'A calibrated decision model rates each spec field and weighs competing hypotheses with probabilities. Its advice is recorded, but never counts as evidence.',
        'landing.acc.clarify.title': 'Clarification tool',
        'landing.acc.clarify.desc': 'When the evidence cannot settle a choice that changes the answer, yourDB asks you instead of guessing, and the result must follow your choice.',
        'landing.secure.local.title': 'Runs locally',
        'landing.secure.local.desc': 'yourDB runs on your own computer or server. Connection settings, conversations and output files stay on that machine.',
        'landing.secure.mcp.title': 'MCP bridge',
        'landing.secure.mcp.desc': 'The agent holds no database connection. Every query goes through an MCP server process, with a database-enforced time limit and bounded results.',
        'landing.secure.guard.title': 'SQL guard',
        'landing.secure.guard.desc': 'Only read-only queries pass. DROP, DELETE, UPDATE, INSERT, ALTER and other writes are refused before they reach the database.',
        'landing.guard.blocked': 'Blocked',
        'landing.guard.allowed': 'Allowed',
        'landing.easy.oneshot.kicker': 'One sentence',
        'landing.easy.oneshot.ask': 'Pull September sales by region, chart it and make a dashboard',
        'landing.easy.oneshot.desc': 'No SQL, no copy-paste between tools. Ask once and get the query, the file, the chart and the dashboard.',
        'landing.format.png.tag': 'PNG',
        'landing.format.png.title': 'Images',
        'landing.format.png.desc': 'Dashboards sent to your phone as pictures, and report charts.',
        'landing.format.chart.tag': 'CHART',
        'landing.format.chart.title': 'Generated charts',
        'landing.format.chart.desc': 'Charts rendered right in the conversation.',
        'landing.format.ai.tag': 'JSON',
        'landing.format.ai.title': 'AI-friendly artifacts',
        'landing.format.ai.desc': 'Each chart comes with a machine-readable record of its spec and data source.',
        'landing.format.csv.tag': 'CSV',
        'landing.format.csv.title': 'CSV tables',
        'landing.format.csv.desc': 'Complete query results for Excel or any other tool.',
        'landing.format.md.tag': 'MD',
        'landing.format.md.title': 'Markdown reports',
        'landing.format.md.desc': 'Structured analysis reports with charts.',
        'landing.format.html.tag': 'HTML',
        'landing.format.html.title': 'HTML dashboards',
        'landing.format.html.desc': 'Standalone, production-grade dashboards in one file.',
        'landing.how.kicker': 'How to use',
        'landing.how.title': 'From connecting a database to your first answer.',
        'landing.how.desc': 'Set it up on the desktop first, then connect your phone whenever you want it there.',
        'landing.how.desktop.title': 'Desktop & web',
        'landing.how.desktop.note': 'set up once',
        'landing.how.desktop.launch.title': 'Launch and sign in',
        'landing.how.desktop.launch.desc': 'Open the yourDB desktop app or the web version and create the first admin account.',
        'landing.how.desktop.connect.title': 'Connect a database',
        'landing.how.desktop.connect.desc': 'Connect MySQL, PostgreSQL or SQLite, and fill in the knowledge base.',
        'landing.how.desktop.ask.title': 'Ask in one sentence',
        'landing.how.desktop.ask.desc': 'Describe the business question, attaching files if you need to.',
        'landing.how.desktop.deliver.title': 'Review and deliver',
        'landing.how.desktop.deliver.desc': 'Check the SQL, the result and the dashboard, then keep asking in the same session.',
        'landing.how.mobile.title': 'Mobile',
        'landing.how.mobile.note': 'optional',
        'landing.how.mobile.scan.title': 'Scan to connect',
        'landing.how.mobile.scan.desc': 'In Settings → Message channels, scan the QR code with your work chat app. The bot is created for you.',
        'landing.how.mobile.bind.title': 'Link your account',
        'landing.how.mobile.bind.desc': 'Get a 6-digit code in settings and send "/bind code" to the bot in a private chat.',
        'landing.how.mobile.ask.title': 'Ask from your phone',
        'landing.how.mobile.ask.desc': 'Ask the way you would ask a colleague. If it needs to clarify, it asks you.',
        'landing.how.mobile.receive.title': 'View the results',
        'landing.how.mobile.receive.desc': 'Answers, charts and dashboards come back in the chat; dashboards arrive as an image with the HTML page attached.',
        'landing.final.title': 'Your data, one sentence away.',
        'landing.final.desc': 'Connect a database and ask your first question.',
        'landing.arch.title': 'yourDB architecture',
        'landing.arch.desc': 'Desktop, web and mobile reach a host, which runs the Data Agent runtime. The runtime reads knowledge and skills on demand, calls the model, and answers through the Answering module, which reaches the database only through an MCP server and publishes files to the workspace.',
        'landing.arch.entry': 'Entry points',
        'landing.arch.entry.desktop': 'DESKTOP · ELECTRON',
        'landing.arch.entry.web': 'WEB · HTTP + SSE',
        'landing.arch.entry.mobile': 'MOBILE · IM BOT',
        'landing.arch.host': 'auth · sessions · files',
        'landing.arch.knowledge': 'six layers · semantic model',
        'landing.arch.onDemand': 'read on demand',
        'landing.arch.runtime': 'Pi agent core · tools · sub-agents',
        'landing.arch.model': 'LLM · any provider',
        'landing.arch.reason': 'reasoning · tool calls',
        'landing.arch.answering': 'spec · gates · publication',
        'landing.arch.jev': 'calibrated judgement',
        'landing.arch.advice': 'advice only',
        'landing.arch.publish': 'publish',
        'landing.arch.mcp': 'read-only · SQL guard',
        'landing.arch.viaMcp': 'separate process · stdio',
        'landing.flowdg.title': 'How an answer is delivered',
        'landing.flowdg.desc': 'A question becomes an Answer Spec. The outer loop settles what to answer, the inner loop settles how; the result query runs only once the spec is sealed, then passes candidate checks before it is published with a receipt and disclosure. A failed check sends it back for revision.',
        'landing.flowdg.start': 'Question → Answer Spec',
        'landing.flowdg.outer': 'Outer loop · what to answer',
        'landing.flowdg.outerDesc': 'one field tree · open fields · necessity rules',
        'landing.flowdg.evidence': 'evidence admission',
        'landing.flowdg.inner': 'Inner loop · how to answer',
        'landing.flowdg.innerDesc': 'exploration queries · choice probes',
        'landing.flowdg.probe': 'choice probe',
        'landing.flowdg.fingerprint': 'result fingerprint',
        'landing.flowdg.midA': 'While anything in the spec is unresolved, ',
        'landing.flowdg.midB': 'the result query does not run.',
        'landing.flowdg.gate': 'Seal → run → candidate checks → realise choices → publish',
        'landing.flowdg.out': 'Delivered: publication receipt + disclosure',
        'landing.flowdg.retry': 'FAIL → REVISE',

        'settings.title': 'Settings',
        'settings.model': 'Model',
        'settings.database': 'Database',
        'settings.environment': 'Environment',
        'settings.modelSettings': 'Model Settings',
        'settings.providers': 'Providers',
        'settings.defaultModelTitle': 'Default Model and Provider',
        'settings.defaultModelSubtitle': 'Agent Working Model',
        'settings.defaultModelHint': 'Tip: To change the working model, select the provider on the left, enable it, and select the desired model.',
        'settings.notSet': 'Not set',
        'settings.historyLimitTitle': 'Chat History Limit',
        'settings.maxTurns': 'Max Dialogue Turns',
        'settings.maxTurnsSubtitle': 'Number of retained turns (0 = unlimited)',
        'settings.maxTokens': 'Max History Tokens',
        'settings.maxTokensSubtitle': 'Max retained tokens (0 = unlimited)',
        'settings.apiKeyTitle': 'API Key',
        'settings.apiKeyPlaceholder': 'To keep current, enter [configured]',
        'settings.supportModels': 'Supported Models',
        'settings.refreshModels': 'Refresh Available Models from API',
        'settings.howToGetToken': 'How to get an API Token?',
        'settings.enableProvider': 'Enable this provider to use its models in chat',
        'settings.save': 'Save',
        'settings.dbSettings': 'MySQL Database Configuration',
        'settings.dbHost': 'Host',
        'settings.dbPort': 'Port',
        'settings.dbUser': 'Username',
        'settings.dbPassword': 'Password',
        'settings.dbPasswordPlaceholder': 'Enter password or leave blank if no auth',
        'settings.dbDatabase': 'Database Name',
        'settings.dbTest': 'Test',
        'settings.testing': 'Testing...',
        'settings.enabled': 'Enabled (Current Worker)',
        'settings.disabled': 'Disabled',
        'settings.apiBaseUrl': 'API base URL',
        'settings.modelName': 'Model name',
        'settings.providerEnabled': 'Enabled (current provider)',
        'settings.providerDisabled': 'Disabled',
        'settings.configLocalHint': 'Configuration is stored locally in this browser. Enabling the provider saves it and reloads the backend with the selected model.',
        'settings.python': 'Python environment',
        'settings.pythonHint': 'Choose the runtime used when the backend executes Python tools.',
        'settings.bundledPython': 'Bundled environment',
        'settings.externalPython': 'External Python',
        'settings.pythonExecutable': 'Python executable',
        'settings.choose': 'Choose',
        'settings.testPython': 'Test',
        'settings.savePython': 'Save',
        'settings.testingPython': 'Testing',
        'settings.saveSuccess': 'Saved',
        'settings.saveFailed': 'Unable to save settings. Check the configuration and try again.',
        'settings.loadFailed': 'Unable to load settings. Try again later.',
        'settings.dbSaveSuccess': 'Database configuration saved and applied.',
        'settings.dbSaveFailed': 'Unable to save database configuration. Check the values and try again.',
        'settings.dbTestSuccess': 'Connection test passed',
        'settings.dbTestFailed': 'Connection test failed',

        'plugins.mcp': 'MCP Settings',
        'plugins.skills': 'Skills Settings',
        'plugins.installed': 'Installed',
        'plugins.addNew': 'Install New',
        'plugins.status': 'Status',
        'plugins.connected': 'Connected',
        'plugins.disconnected': 'Disconnected',
        'plugins.toolsNum': 'Total Tools',
        'plugins.addNewServer': 'Add New MCP Server',
        'plugins.installLabel': 'Install via Command / Package',
        'plugins.installPlaceholder': 'e.g., npx -y @server/foo',
        'plugins.envLabel': 'Environment Variables (JSON)',
        'plugins.envPlaceholder': '{"TOKEN": "abc"} (Optional)',
        'plugins.serverName': 'Server Identifier',
        'plugins.installing': 'Installing...',
        'plugins.install': 'Install',
        'plugins.noServers': 'No MCP servers configured',
        'plugins.settings': 'Settings',
        'plugins.mcpDesc': 'Manage MCP Server configurations, connection states, and bridge tools.',
        'plugins.refresh': 'Refresh',
        'plugins.add': 'Add',
        'plugins.disabled': 'Disabled',
        'plugins.noDesc': 'No description',
        'plugins.edit': 'Edit',
        'plugins.noSrvHint': 'No MCP server yet, click "Add" on the top right.',
        'plugins.unnamedSrv': 'Unnamed server',
        'plugins.selectHint': 'Please select an MCP server from the left to edit.',
        'plugins.searchSkill': 'Search Skill',
        'plugins.noSkills': 'No Skills',
        'plugins.loadingSkills': 'Loading Skills...',
        'plugins.reconnect': 'Reconnect',
        'plugins.enable': 'Enable',
        'plugins.disable': 'Disable',
        'plugins.hostManaged': 'Host managed by Data Agent',
        'plugins.serverSettings': 'MCP server settings',
        'plugins.serverHint': 'Supports stdio / http / sse. The stdio path is currently preferred.',
        'plugins.name': 'Name',
        'plugins.transport': 'Transport',
        'plugins.command': 'Command',
        'plugins.scriptArgs': 'Script or URL',
        'plugins.url': 'URL',
        'plugins.arguments': 'Arguments (JSON array)',
        'plugins.environment': 'Environment variables (env)',
        'plugins.headers': 'Request headers',
        'plugins.toolPrefix': 'Tool prefix',
        'plugins.serverType': 'Server type',
        'plugins.description': 'Description',
        'plugins.enableServer': 'Enable this MCP server',
        'plugins.deleteConfig': 'Delete configuration',
        'plugins.test': 'Test MCP',
        'plugins.saveConfig': 'Save configuration',
        'plugins.discoveredTools': 'Discovered tools',
        'plugins.transportSummary': 'Transport',
        'plugins.typeSummary': 'Type',
        'plugins.toolsSummary': 'Tools',
        'plugins.path': 'Path',
        'plugins.whenToUse': 'When to use',
        'plugins.configured': 'Configured ({count})',
        'plugins.noSearchResults': 'No Skills match your search.',
        'plugins.invalidJson': 'Some MCP JSON fields are invalid. Check the examples and try again.',
        'plugins.updateFailed': 'Unable to update the MCP server. Try again.',
        'plugins.reconnectFailed': 'Unable to reconnect the MCP server. Try again.',
        'plugins.saveFailed': 'Unable to save the MCP configuration. Check the fields and try again.',
        'plugins.loadFailed': 'Unable to load MCP configuration. Try again.',
        'plugins.testFailed': 'MCP test failed. Check the server configuration and try again.',
        'plugins.loadSkillsFailed': 'Unable to load Skills. Try again.',
        'plugins.notConfigured': 'Not configured',
        'plugins.connecting': 'Connecting',
        'plugins.error': 'Error',

        'chat.workspaceEmpty': 'No files attached.',
        'chat.stop': 'Stop',
        'chat.send': 'Send',
        'chat.placeholder': 'Enter your request or question here...',
        'chat.you': 'You',
        'chat.agent': 'Agent',
        'chat.needsClarification': 'Needs your clarification',
        'chat.inputAnswer': 'Enter your answer...',
        'chat.submitting': 'Submitting...',
        'chat.submit': 'Submit',
        'chat.steerHint': 'Additional instructions will be sent as steer/follow-up',
        'chat.status': 'Status',
        'chat.stopped': 'Stopped',
        'chat.uploadTooltip': 'Upload and attach files',
        'chat.attachedFiles': 'Attached files',
        'chat.removeAttachment': 'Remove {name}',
        'chat.steerPlaceholder': 'Steering instructions...',
        'chat.startMessage': 'Send a message to start...',
        'chat.pageTitle': 'Agent chat',
        'chat.agents': 'Agents',
        'chat.details': 'Details',
        'chat.resizeWidth': 'Resize chat panel width with arrow keys',
        'chat.openDetails': 'Open details',
        'chat.closeDetails': 'Close details',
        'chat.clarificationTitle': 'Needs your clarification',
        'chat.clarificationOptions': 'Suggested answers',
        'chat.clarificationEditHint': 'Pick an option to edit it, or type your own answer...',
        'chat.requestFailed': 'Unable to complete the request.',
        'chat.retryHint': 'Check your connection or configuration and try again.',
        'chat.uploadFailed': 'Unable to upload the file. Check the file and try again.',
        'chat.toolCalling': 'Calling tool: {name}',
        'chat.toolCompleted': 'Completed tool: {name}',
        'chat.toolFailed': 'Tool failed: {name}',
        'chat.skillActivated': 'Skill activated: {name}',
        'chat.skillLoaded': 'Loaded: {name}',
        'chat.streamReconnecting': 'Connection lost, reconnecting…',
        'chat.subagentLine': 'subagent: {name}  Tool: {tool}/{count}  Elapsed: {elapsed}  Output: {output}',
        'chat.subagentOutputPending': 'pending',
        'chat.subagentOutputProduced': 'produced',
        'chat.subagentOutputNone': 'none ({status})',
        'chat.subagentStatus.running': 'running',
        'chat.subagentStatus.completed': 'no report',
        'chat.subagentStatus.failed': 'failed',
        'chat.subagentStatus.cancelled': 'cancelled',
        'chat.subagentStatus.interrupted': 'interrupted',
        'chat.subagentStatus.timed_out': 'timed out',
        'chat.subagentStatus.budget_exhausted': 'budget exhausted',
        'chat.subagentStatus.invalid_output': 'invalid report',
        'chat.subagentStatus.abort_unconfirmed': 'abort unconfirmed',
        'chat.phaseValidatingSql': 'Validating SQL',
        'chat.phaseRunningQuery': 'Running query',
        'chat.phaseRunningTool': 'Running tool',
        'chat.phaseDoneTool': 'Completed tool',
        'chat.phaseErrorTool': 'Tool failed',
        'chat.retryNotice': 'Retrying {operation}: {attempt}/{max} in {delay}s',
        'chat.semanticWaiting': 'Semantic context is still preparing. You can continue with other questions.',
        
        'tools.processing': 'Thinking...',
        'tools.statusError': 'Error',
        'tools.statusDone': 'Done',
        'tools.statusRunning': 'Thinking',
        'tools.args': 'Arguments',
        'tools.result': 'Result',
        'tools.details': 'Details',
        'tools.copy': 'Copy',
        'tools.noCalls': 'No tool calls yet',
        'tools.noCallsHint': 'Tool details will appear here while the agent works.',

        'widgets.true': 'Yes',
        'widgets.false': 'No',
        'widgets.legacyEcharts': 'This chart came from an earlier version and is no longer drawn. Ask again to rebuild it from published data.',
        'widgets.metric': 'Metric',
        'widgets.column': 'Column',
        'widgets.dataPoint': 'Data Point',
        'widgets.step': 'Step',
        'widgets.preview': 'Preview',
        'widgets.download': 'Download',
        'widgets.renderFail': 'Widget render failed',

        'preview.title': 'File preview',
        'preview.file': 'File',
        'preview.close': 'Close preview',
        'preview.openExternal': 'Open in browser',
        'preview.unsupported': 'This file type does not support inline preview yet.',
        'preview.loading': 'Loading preview…',
        'preview.loadError': 'Unable to load the preview. Check the backend service or file permissions.',
        'preview.csvColumn': 'Column {number}',
        'preview.csvLimit': 'Showing the first 200 rows',
        'preview.resize': 'Resize preview window',
        'editor.edit': 'Edit file',
        'editor.save': 'Save file',
        'editor.close': 'Close file editor',
        'editor.loading': 'Loading file…',
        'editor.loadFailed': 'Unable to load the file. Try again later.',
        'editor.saveFailed': 'Unable to save the file. Check your connection and try again.',
        'semantic.close': 'Close semantic asset',
        'semantic.loading': 'Loading semantic asset…',
        'semantic.loadFailed': 'Unable to load the semantic asset. Try again later.',

        'onboarding.badge': 'Desktop Setup',
        'onboarding.titleLine1': 'Connect Data Agent',
        'onboarding.titleLine2': 'to your model provider',
        'onboarding.description': 'Choose your language, connect one model provider, and you can start using the local assistant right away.',
        'onboarding.featureLabel': 'What this setup does',
        'onboarding.featureOne': 'Encrypts desktop secrets with Electron safeStorage before reuse',
        'onboarding.featureTwo': 'Keeps provider and database settings together in one startup flow',
        'onboarding.featureThree': 'Lets you switch the interface language before entering the app',
        'onboarding.browserWarning': 'Browser dev mode detected. Keys will be sent to the backend for this session, but they will not be persisted in localStorage.',
        'onboarding.formEyebrow': 'Getting Started',
        'onboarding.formTitle': 'Finish the first-run configuration',
        'onboarding.formDescription': 'Set your preferred language first, then choose the provider you want Data Agent to use.',
        'onboarding.languageLabel': 'Interface language',
        'onboarding.languageHint': 'This choice is saved and reused the next time you open the desktop app.',
        'onboarding.language.zh': 'Chinese',
        'onboarding.language.en': 'English',
        'onboarding.providerAria': 'Model provider',
        'onboarding.provider.openai': 'OpenAI compatible',
        'onboarding.provider.anthropic': 'Anthropic',
        'onboarding.apiKey': 'API key',
        'onboarding.baseUrl': 'Base URL',
        'onboarding.defaultModel': 'Default model',
        'onboarding.optionalMySql': 'Optional MySQL connection',
        'onboarding.host': 'Host',
        'onboarding.port': 'Port',
        'onboarding.user': 'User',
        'onboarding.password': 'Password',
        'onboarding.databaseName': 'Database name',
        'onboarding.verify': 'Verify and start',
        'onboarding.verifying': 'Verifying...',
        'onboarding.errorMissingKey': 'Please enter at least one API key before continuing.',
        'onboarding.errorVerify': 'LLM verification failed',
        'onboarding.errorSave': 'Failed to save configuration',

        'task.new': 'New task',
        'task.created': 'Task created',
        'task.emptyPrompt': 'Create a task to begin.',
        'task.confirmDelete': 'Delete task “{name}” and all of its sessions?',
        'session.new': 'New session',
        'session.create': 'New session',
        'session.empty': 'No sessions',
        'session.emptyPrompt': 'This task has no sessions. Create a session when you are ready to start a conversation.',
        'session.confirmDelete': 'Delete session “{name}”?',
        'knowledge.loadFailed': 'Failed to load knowledge base',

        'semantic.toolbarLabel': 'Semantic asset view mode',
        'semantic.split': 'Split',
        'semantic.code': 'Code',
        'semantic.visual': 'Visual',
        'semantic.narrowHint': 'Switched to single-column tabs for narrow screen',
        'semantic.manifestOnly': 'Defined by system manifest',
        'semantic.manifestOnlyDesc': 'No standalone YAML file. To customize, create an Overlay via KTX.',
        'semantic.yamlSource': 'YAML source',
        'semantic.businessKnowledge': 'Business Knowledge YAML',
        'semantic.queryable': 'Queryable',
        'semantic.noPhysicalSource': 'No physical source declared',
        'semantic.defaultTime': 'Default time: ',
        'semantic.tags': 'Tags',
        'semantic.copy': 'Copy code',
        'semantic.copied': 'Copied',
        'semantic.noFields': 'No fields defined',
        'semantic.fields': 'Fields',
        'semantic.inheritedFromManifest': 'Inherited from manifest'
    },
    zh: {
        'sidebar.navigation': '工作区导航',
        'sidebar.open': '打开侧边栏',
        'sidebar.close': '关闭侧边栏',
        'sidebar.newTask': '新建任务',
        'sidebar.currentTask': '当前任务',
        'sidebar.chat': '对话',
        'sidebar.knowledge': '知识库',
        'sidebar.plugins': '插件管理',
        'sidebar.metrics': '指标',
        'sidebar.settings': '设置',
        'sidebar.langToggle': 'Switch to English',
        'sidebar.semantic': '语义模型',
        'sidebar.language': '语言',
        'sidebar.logout': '退出',

        'accessibility.skipToContent': '跳转到主要内容',
        'common.loading': '加载中…',
        'common.close': '关闭',
        'common.edit': '编辑',
        'common.save': '保存',
        'common.delete': '删除',
        'common.choose': '选择',
        'common.retry': '重试',
        'common.hostManaged': '由 Data Agent 托管',
        'common.noKnowledgeFiles': '暂无知识库文件。',
         'common.noKnowledgeFilesHint': '点击上方「新建」或「导入」添加；也可将文件放入数据目录的 knowledge 文件夹。',
        'common.knowledgeNew': '新建',
        'common.knowledgeImport': '导入',
        'common.knowledgeImported': '已导入',
        'common.knowledgeBuiltin': '内置',
        'common.knowledgeBuiltinHint': '随应用发布并随版本更新，只读。',
        'common.knowledgePlaceholder': '待填写',
        'common.knowledgePlaceholderHint': '占位文档：填写内容后 Agent 才会使用它。',
        'common.knowledgeNamePrompt': '文件名（例如 doc/notes.md）：',
        'common.noSemanticAssetsHint': '会自动扫描语义项目目录；点击刷新可重新扫描。',
        'common.semanticRefresh': '刷新', 
        'common.noSemanticAssets': '暂无可用语义资产。',
        'common.requestFailed': '请求失败。',
        'common.retryHint': '请检查网络或配置后重试。',

        'app.preparing': '正在准备 Data Agent...',
        'app.startupError': 'Data Agent 无法初始化本地运行时，请检查配置后重试。',
        'app.retry': '重试',
        'desktop.file': '文件',
        'desktop.edit': '编辑',
        'desktop.view': '视图',
        'desktop.window': '窗口',
        'desktop.help': '帮助',
        'desktop.menu': '应用菜单',

        'auth.registerSubtitle': '创建首个管理员账号',
        'auth.loginSubtitle': '登录后继续',
        'auth.username': '用户名',
        'auth.password': '密码',
        'auth.createAccount': '创建账号',
        'auth.signIn': '登录',
        'auth.submitting': '请稍候',
        'auth.useExisting': '使用已有账号',
        'auth.createFirst': '创建首个账号',
        'auth.errorFallback': '认证失败',

        'landing.nav.label': '页面导航',
        'landing.nav.who': '适合谁',
        'landing.nav.what': '能做什么',
        'landing.nav.where': '多端',
        'landing.nav.build': '如何构建',
        'landing.nav.why': '为什么选我们',
        'landing.nav.how': '如何使用',
        'landing.enterApp': '进入应用',
        'landing.hero.eyebrow': '专为数据场景打造的智能 Agent',
        'landing.hero.subtitle': '取数、导出、写报告、出看板，一句话直出。电脑、网页、手机，随时随地。',
        'landing.hero.primary': '开始使用 yourDB',
        'landing.hero.secondary': '看看适不适合我',
        'landing.hero.platforms': '可用平台',
        'landing.demo.label': '产品演示：从一个新的 yourDB 工作区开始，对 delivery_center 数据库提一句需求，生成配送数据现状看板',
        'landing.demo.play': '播放演示',
        'landing.demo.pause': '暂停演示',
        'landing.demo.chapters': '演示章节',
        'landing.demo.ch.new': '新建任务',
        'landing.demo.ch.ask': '提问',
        'landing.demo.ch.explore': '探索',
        'landing.demo.ch.query': '查询',
        'landing.demo.ch.dashboard': '看板',
        'landing.demo.task1': '履约体验复盘',
        'landing.demo.task2': '区域销售周报',
        'landing.demo.question': '请基于 delivery_center 数据库，生成一张配送数据现状看板。',
        'landing.demo.reasoning': '先摸清表结构和行数，再为每个视图确定口径。',
        'landing.demo.reasoningDone': '思考内容',
        'landing.demo.m1': '我先读取方法类知识，并并行委派信息收集。',
        'landing.demo.m2': 'orders 表实测 0 行，按月趋势无法计算，也不拿总体占比顶替。改用 deliveries / payments 出现状看板。',
        'landing.demo.m3': '看板已生成。',
        'landing.demo.file': '看板文件',
        'landing.demo.dash.title': 'delivery_center 配送数据现状看板',
        'landing.demo.dash.chip1': '配送单 378,843 条',
        'landing.demo.dash.chip2': '支付记录 400,834 笔',
        'landing.demo.dash.chip3': '全量快照',
        'landing.demo.dash.asof': '数据快照 · 2026-10-02',
        'landing.demo.dash.summary': '本期结论',
        'landing.demo.dash.f1': '的配送单为已送达（DELIVERED），配送状态高度集中、异常面很窄',
        'landing.demo.dash.f2': '的配送单距离落在 1–3 km，运力可按短途场景优先配置',
        'landing.demo.dash.f3': '的支付笔数为 ONLINE，支付通道高度集中',
        'landing.demo.dash.status': '配送单状态构成',
        'landing.demo.dash.delivered': '已送达',
        'landing.demo.dash.cancelled': '已取消',
        'landing.demo.dash.delivering': '配送中',
        'landing.demo.dash.unit': '单',
        'landing.demo.dash.share': '占比',
        'landing.demo.dash.distTitle': '配送距离集中在 1–3 km，占 48.92%',
        'landing.demo.dash.distSub': '距离非空配送单 378,770 条 · 标签为占比 · 单位：单 / %',
        'landing.demo.dash.donutTitle': '配送状态构成：已送达占 98.03%',
        'landing.demo.dash.donutSub': '全部配送单 378,843 条 · 单位：单',
        'landing.demo.dash.payTitle': '支付方式高度集中于 ONLINE，占 77.93%',
        'landing.demo.dash.paySub': '全部支付记录 400,834 笔 · 标签为占比 · 单位：笔 / %',
        'landing.who.kicker': '适合谁',
        'landing.who.title': '如果你是下面其中之一，欢迎试试 yourDB。',
        'landing.who.desc': '专为数据场景打造的智能 Agent，把日常的数据需求从人身上卸下来。',
        'landing.who.ops.name': '不敢打扰数仓工程师的 I 人运营',
        'landing.who.ops.pain': '想要个数，可这周已经找数仓同学两次了。',
        'landing.who.ops.fix': '直接问 yourDB，不用排队，也不用寒暄。',
        'landing.who.ops.ask': '上周新客转化率是多少？',
        'landing.who.engineer.name': '被多方需求随时打断的数仓工程师',
        'landing.who.engineer.pain': '一天被拉去取十次临时数，正事一拖再拖。',
        'landing.who.engineer.fix': '把常规取数交给 yourDB，口径按你的知识库来。',
        'landing.who.engineer.ask': '把 9 月各渠道 GMV 导出成 CSV',
        'landing.who.analyst.name': '被多重任务压倒的数据分析师',
        'landing.who.analyst.pain': '查询、做表、写报告、做看板，件件都急。',
        'landing.who.analyst.fix': '一句话先把报告和看板做出来，你只需要检查和判断。',
        'landing.who.analyst.ask': '做一份华东区三季度经营分析报告',
        'landing.who.boss.name': '随时想看数据的企业老总',
        'landing.who.boss.pain': '人在路上，也想知道今天生意怎么样。',
        'landing.who.boss.fix': '打开手机问一句，看板直接发回对话里。',
        'landing.who.boss.ask': '今天各门店销售额排名',
        'landing.what.kicker': '能做什么',
        'landing.what.title': '日常查询、数据导出、分析报告、分析看板。',
        'landing.what.desc': '四类日常数据工作，都从一句话开始。',
        'landing.cap.try': '试试这样问',
        'landing.cap.gets': '你会得到',
        'landing.cap.query.title': '日常数据查询',
        'landing.cap.query.desc': '用大白话提问。yourDB 按你的口径写出只读 SQL 并执行，查询语句和结果都摆在你面前。',
        'landing.cap.query.ask': '9 月以来各区域销售额',
        'landing.cap.query.output': '答案、对应的 SQL 与结果表',
        'landing.cap.query.prompt': '9 月以来各区域销售额',
        'landing.cap.export.title': '数据导出',
        'landing.cap.export.desc': '把经过验证的完整结果导出为 CSV，直接用 Excel 或下游工具打开。',
        'landing.cap.export.ask': '把 9 月所有订单导出成 CSV',
        'landing.cap.export.output': '一份完整的 CSV 文件',
        'landing.cap.report.title': '分析报告',
        'landing.cap.report.desc': '摘要、数据概览、关键发现、图表与建议，生成结构化的 Markdown 报告。',
        'landing.cap.report.ask': '做一份华东区三季度经营分析报告',
        'landing.cap.report.output': '一份带图表的 Markdown 报告',
        'landing.cap.report.docTitle': '华东区 · 三季度经营分析',
        'landing.cap.report.summary': '摘要',
        'landing.cap.report.summaryText': '三季度销售额 1,284 万，环比 +6.2%，电子产品贡献最大。',
        'landing.cap.report.findings': '关键发现',
        'landing.cap.report.f1': '电子产品环比 +11.4%，增速居各品类之首。',
        'landing.cap.report.f2': '延迟超过 3 天的订单，差评率是准时订单的两倍。',
        'landing.cap.dashboard.title': '数据分析看板',
        'landing.cap.dashboard.desc': '商用级独立 HTML 看板，每个视图都来自经过验证、已发布的查询结果。',
        'landing.cap.dashboard.ask': '请基于 delivery_center 数据库，生成一张配送数据现状看板',
        'landing.cap.dashboard.output': '一个 HTML 看板文件',
        'landing.dash.delivery.name': '配送数据现状',
        'landing.dash.delivery.alt': '基于 Delivery Center 公开数据集生成的配送数据现状看板',
        'landing.dash.delivery.note': '真实生成 · Delivery Center 公开数据集',
        'landing.where.kicker': '在哪里用',
        'landing.where.title': '电脑、网页、手机，多端同步。',
        'landing.where.desc': '刚离开电脑，突然来了需求？不用担心，打开手机，就能完成数据需求。',
        'landing.where.sync': '桌面端、网页端、手机端状态同步',
        'landing.where.desktop': '桌面端',
        'landing.where.web': '网页端',
        'landing.where.mobile': '手机端',
        'landing.where.point.dashboard': '看板以图片直接发回，并附上 HTML 页面',
        'landing.where.point.clarify': '问题有歧义时，它会在对话里直接问你',
        'landing.where.point.new': '发送 /new 开始新对话；长时间未聊天会自动开启新会话',
        'landing.where.point.access': '只有绑定了账号、或经成员批准的人才能使用',
        'landing.phone.label': '手机上与 yourDB 的对话',
        'landing.phone.status': '在线',
        'landing.phone.q1': '这周华东区销售额怎么样？',
        'landing.phone.a1': '华东区本周销售额 1,284 万，环比 +6.2%。看板如下。',
        'landing.phone.chartTitle': '华东区 · 周销售额',
        'landing.phone.q2': '哪个品类涨得最多？',
        'landing.phone.a2': '电子产品，环比 +11.4%。需要按城市拆开看吗？',
        'landing.phone.input': '发送给 yourDB',
        'landing.build.kicker': '如何构建',
        'landing.build.title': '从入口到数据库，每一层各司其职。',
        'landing.build.desc': '所有入口都进入同一个运行时：知识与技能按需读取，答案经过 Answering 模块，数据库只经由 MCP 访问。',
        'landing.why.kicker': '为什么选我们',
        'landing.why.title': '准确、安全、便捷。',
        'landing.why.desc': '三个承诺，每一个都有具体的机制支撑。',
        'landing.why.accurate.title': '准确',
        'landing.why.accurate.desc': '答案到你手上之前，先核对它回答的是不是你的问题。确定不了的，要么问你，要么明说。',
        'landing.why.secure.title': '安全',
        'landing.why.secure.desc': 'Agent 从不直连你的数据库，它执行的任何语句都改不了你的数据。',
        'landing.why.easy.title': '便捷',
        'landing.why.easy.desc': '绘图、取数、看板、分析，一句话直出；哪台设备都能用，要什么格式给什么格式。',
        'landing.acc.answer.title': 'Answer 模块',
        'landing.acc.answer.desc': '问题被落成一份版本化的答案规格：有证据的硬约束、待验证的假设、尚未确定的选择。结果发布之前，SQL 必须先对得上这份规格。',
        'landing.acc.hypothesis.title': '假设检验系统',
        'landing.acc.hypothesis.desc': '模型推断出的每一种理解都登记为假设，必须用已准入的证据支持或推翻，之后才能算数。',
        'landing.acc.loop.title': '双循环校验',
        'landing.acc.loop.desc': '外层循环收敛"答什么"，内层循环收敛"怎么答"。实现失败不改变业务定义；定义一旦变化，实现必须重新审视。',
        'landing.acc.jev.title': 'Jev 决策引擎',
        'landing.acc.jev.desc': '校准决策模型逐项判断规格字段，并用概率比较相互竞争的假设。它的建议会被记录，但永远不算证据。',
        'landing.acc.clarify.title': '用户澄清工具',
        'landing.acc.clarify.desc': '证据无法确定、又会改变答案的选择，yourDB 会先问你而不是去猜，最终结果必须按你的选择落实。',
        'landing.secure.local.title': '本地运行',
        'landing.secure.local.desc': 'yourDB 运行在你自己的电脑或服务器上，数据库连接配置、会话记录和产出文件都留在这台机器上。',
        'landing.secure.mcp.title': 'MCP 桥接',
        'landing.secure.mcp.desc': 'Agent 不持有任何数据库连接，每条查询都经由 MCP 服务进程中转，执行时限由数据库强制，结果有界。',
        'landing.secure.guard.title': 'SQL 守卫',
        'landing.secure.guard.desc': '只放行只读查询，DROP、DELETE、UPDATE、INSERT、ALTER 等写操作在到达数据库之前就被拦截。',
        'landing.guard.blocked': '已拦截',
        'landing.guard.allowed': '已放行',
        'landing.easy.oneshot.kicker': '一句直出',
        'landing.easy.oneshot.ask': '取 9 月各区域销售额，画成图，再做个看板',
        'landing.easy.oneshot.desc': '不用写 SQL，不用在工具之间来回复制。问一次，查询、文件、图表和看板一起给你。',
        'landing.format.png.tag': 'PNG',
        'landing.format.png.title': '图片',
        'landing.format.png.desc': '发到手机上的看板截图，以及报告配图。',
        'landing.format.chart.tag': 'CHART',
        'landing.format.chart.title': '生成式图表',
        'landing.format.chart.desc': '在对话中直接渲染的图表。',
        'landing.format.ai.tag': 'JSON',
        'landing.format.ai.title': 'AI 友好型产物',
        'landing.format.ai.desc': '每张图表都附带机器可读的描述与数据来源记录。',
        'landing.format.csv.tag': 'CSV',
        'landing.format.csv.title': 'CSV 表格',
        'landing.format.csv.desc': '完整查询结果，Excel 等工具直接打开。',
        'landing.format.md.tag': 'MD',
        'landing.format.md.title': 'Markdown 报告',
        'landing.format.md.desc': '结构化的分析报告，图文并茂。',
        'landing.format.html.tag': 'HTML',
        'landing.format.html.title': 'HTML 看板',
        'landing.format.html.desc': '单文件、商用级的独立看板。',
        'landing.how.kicker': '如何使用',
        'landing.how.title': '从连接数据库，到第一个答案。',
        'landing.how.desc': '先在桌面端完成设置；想在手机上用时，再接入手机端。',
        'landing.how.desktop.title': '桌面端与网页端',
        'landing.how.desktop.note': '一次设置',
        'landing.how.desktop.launch.title': '启动并登录',
        'landing.how.desktop.launch.desc': '打开 yourDB 桌面端或网页端，创建首个管理员账号。',
        'landing.how.desktop.connect.title': '连接数据库',
        'landing.how.desktop.connect.desc': '连接 MySQL、PostgreSQL 或 SQLite，并完善知识库。',
        'landing.how.desktop.ask.title': '用一句话提问',
        'landing.how.desktop.ask.desc': '描述你的业务问题，需要时可以附带文件。',
        'landing.how.desktop.deliver.title': '检查并交付',
        'landing.how.desktop.deliver.desc': '查看 SQL、结果与看板，在同一个会话里继续追问。',
        'landing.how.mobile.title': '手机端',
        'landing.how.mobile.note': '可选',
        'landing.how.mobile.scan.title': '扫码接入',
        'landing.how.mobile.scan.desc': '在 设置 → 消息渠道 中用办公聊天应用扫码，机器人会自动创建。',
        'landing.how.mobile.bind.title': '绑定账号',
        'landing.how.mobile.bind.desc': '在设置中获取 6 位验证码，私聊机器人发送「/bind 验证码」。',
        'landing.how.mobile.ask.title': '在手机上提问',
        'landing.how.mobile.ask.desc': '像问同事一样提问；需要澄清时，它会反过来问你。',
        'landing.how.mobile.receive.title': '查看结果',
        'landing.how.mobile.receive.desc': '答案、图表和看板直接发回对话；看板以图片呈现，HTML 页面作为文件随附。',
        'landing.final.title': '你的数据，只差一句话。',
        'landing.final.desc': '连接数据库，提出你的第一个问题。',
        'landing.arch.title': 'yourDB 系统架构',
        'landing.arch.desc': '桌面端、网页端与手机端经由宿主进入 Data Agent 运行时。运行时按需读取知识与技能、调用模型，并通过 Answering 模块作答；Answering 只经由 MCP 服务访问数据库，并把产物发布到工作区。',
        'landing.arch.entry': '入口',
        'landing.arch.entry.desktop': '桌面端 · ELECTRON',
        'landing.arch.entry.web': '网页端 · HTTP + SSE',
        'landing.arch.entry.mobile': '手机端 · IM 机器人',
        'landing.arch.host': '认证 · 会话 · 文件',
        'landing.arch.knowledge': '六层上下文 · 语义模型',
        'landing.arch.onDemand': '按需读取',
        'landing.arch.runtime': 'Pi Agent Core · 工具 · 子 Agent',
        'landing.arch.model': 'LLM · 任意 Provider',
        'landing.arch.reason': '推理 · 工具调用',
        'landing.arch.answering': '答案规格 · 门控 · 发布',
        'landing.arch.jev': '校准决策 · 规格对齐',
        'landing.arch.advice': '仅作建议',
        'landing.arch.publish': '发布产物',
        'landing.arch.mcp': '只读 · SQL 守卫',
        'landing.arch.viaMcp': '独立进程 · stdio',
        'landing.flowdg.title': '一个答案是怎样交付的',
        'landing.flowdg.desc': '问题先落成答案规格。外层循环收敛"答什么"，内层循环收敛"怎么答"；规格封存后才执行结果查询，通过候选检查后，连同发布凭据与披露一起交付。检查不通过则回到修订。',
        'landing.flowdg.start': '用户提问 → 答案规格',
        'landing.flowdg.outer': '外层循环 · 答什么',
        'landing.flowdg.outerDesc': '字段树 · 待定字段 · 必要性规则',
        'landing.flowdg.evidence': '证据准入',
        'landing.flowdg.inner': '内层循环 · 怎么答',
        'landing.flowdg.innerDesc': '探索查询 · 选择探针',
        'landing.flowdg.probe': '选择探针',
        'landing.flowdg.fingerprint': '结果指纹',
        'landing.flowdg.midA': '规格里还有未声明或待定的字段，',
        'landing.flowdg.midB': '结果查询就不会执行。',
        'landing.flowdg.gate': '封存规格 → 执行 → 候选检查 → 选择落实 → 发布',
        'landing.flowdg.out': '交付：发布凭据 + 披露',
        'landing.flowdg.retry': '未通过 → 修订',

        'settings.title': '系统设置',
        'settings.model': '模型',
        'settings.database': '数据库',
        'settings.environment': '环境',
        'settings.modelSettings': '模型设置',
        'settings.providers': '供应商',
        'settings.defaultModelTitle': '配置默认模型和供应商',
        'settings.defaultModelSubtitle': 'Agent 工作模型',
        'settings.defaultModelHint': '提示：要更改工作模型，请在左侧选择对应的供应商，然后开启供应商并选择所需模型。',
        'settings.notSet': '未设置',
        'settings.historyLimitTitle': '对话历史限制',
        'settings.maxTurns': '最大对话轮次',
        'settings.maxTurnsSubtitle': '保留的对话轮次数量（0 = 不限制）',
        'settings.maxTokens': '最大历史 Token 数',
        'settings.maxTokensSubtitle': '对话中的最大 Token 数量（0 = 不限制）',
        'settings.apiKeyTitle': 'API 密钥',
        'settings.apiKeyPlaceholder': '留空表示不修改，如有请填写',
        'settings.supportModels': '支持的模型',
        'settings.refreshModels': '刷新模型列表',
        'settings.howToGetToken': '如何获取 API 令牌？',
        'settings.enableProvider': '开启此供应商以在聊天时使用其模型',
        'settings.save': '保存',
        'settings.dbSettings': 'MySQL 数据库配置',
        'settings.dbHost': '主机地址',
        'settings.dbPort': '端口',
        'settings.dbUser': '用户名',
        'settings.dbPassword': '密码',
        'settings.dbPasswordPlaceholder': '输入密码，若无请留空',
        'settings.dbDatabase': '数据库名称',
        'settings.dbTest': '测试',
        'settings.testing': '测试中...',
        'settings.enabled': '已启用 (当前工作平台)',
        'settings.disabled': '已停用',
        'settings.apiBaseUrl': 'API 基础地址',
        'settings.modelName': '模型名称',
        'settings.providerEnabled': '已启用（当前供应商）',
        'settings.providerDisabled': '已停用',
        'settings.configLocalHint': '配置保存在当前浏览器本地。开启供应商后会保存配置，并使用选中的模型重新加载后端。',
        'settings.python': 'Python 环境',
        'settings.pythonHint': '选择后端执行 Python 工具时使用的运行环境。',
        'settings.bundledPython': '内置环境',
        'settings.externalPython': '外部 Python',
        'settings.pythonExecutable': 'Python 可执行文件',
        'settings.choose': '选择',
        'settings.testPython': '测试',
        'settings.savePython': '保存',
        'settings.testingPython': '测试中',
        'settings.saveSuccess': '已保存',
        'settings.saveFailed': '无法保存设置，请检查配置后重试。',
        'settings.loadFailed': '无法加载设置，请稍后重试。',
        'settings.dbSaveSuccess': '数据库配置已保存并应用。',
        'settings.dbSaveFailed': '无法保存数据库配置，请检查填写内容后重试。',
        'settings.dbTestSuccess': '连接测试成功',
        'settings.dbTestFailed': '连接测试失败',

        'plugins.mcp': 'MCP 设置',
        'plugins.skills': 'Skills 设置',
        'plugins.installed': '已安装',
        'plugins.addNew': '安装新插件',
        'plugins.status': '状态',
        'plugins.connected': '已连接',
        'plugins.disconnected': '未连接',
        'plugins.toolsNum': '工具数量',
        'plugins.addNewServer': '添加新 MCP 服务',
        'plugins.installLabel': '运行命令 / 包名',
        'plugins.installPlaceholder': '例：npx -y @server/foo',
        'plugins.envLabel': '环境变量 (JSON格式)',
        'plugins.envPlaceholder': '{"KEY": "value"}（可选）',
        'plugins.serverName': '服务标识符',
        'plugins.installing': '安装中...',
        'plugins.install': '安装',
        'plugins.noServers': '暂无 MCP 服务器配置',
        'plugins.settings': '设置',
        'plugins.mcpDesc': '管理 MCP Server 配置、连接状态与桥接工具。',
        'plugins.refresh': '刷新',
        'plugins.add': '添加',
        'plugins.disabled': '已禁用',
        'plugins.noDesc': '暂无描述',
        'plugins.edit': '编辑',
        'plugins.noSrvHint': '还没有 MCP server，点击右上角“添加”。',
        'plugins.unnamedSrv': '未命名 server',
        'plugins.selectHint': '请选择左侧的 MCP server 进行编辑。',
        'plugins.searchSkill': '搜索 Skill',
        'plugins.noSkills': '暂无 Skills',
        'plugins.loadingSkills': '正在加载 Skills...',
        'plugins.reconnect': '重连',
        'plugins.enable': '启用',
        'plugins.disable': '禁用',
        'plugins.hostManaged': '由 Data Agent 托管',
        'plugins.serverSettings': 'MCP Server 设置',
        'plugins.serverHint': '支持 stdio / http / sse 配置，当前前端优先接 stdio 主链路。',
        'plugins.name': '名称',
        'plugins.transport': '传输方式',
        'plugins.command': '命令',
        'plugins.scriptArgs': '脚本或 URL',
        'plugins.url': 'URL',
        'plugins.arguments': '参数（JSON 数组）',
        'plugins.environment': '环境变量（env）',
        'plugins.headers': '请求头',
        'plugins.toolPrefix': '工具前缀',
        'plugins.serverType': '服务类型',
        'plugins.description': '简介描述',
        'plugins.enableServer': '启用该 MCP Server',
        'plugins.deleteConfig': '删除配置',
        'plugins.test': '测试 MCP',
        'plugins.saveConfig': '保存配置',
        'plugins.discoveredTools': '发现工具',
        'plugins.transportSummary': '传输方式',
        'plugins.typeSummary': '类型',
        'plugins.toolsSummary': '工具数',
        'plugins.path': '路径',
        'plugins.whenToUse': '使用时机',
        'plugins.configured': '已配置（{count}）',
        'plugins.noSearchResults': '没有匹配的 Skill。',
        'plugins.invalidJson': '部分 MCP JSON 字段格式不正确，请按示例修正后重试。',
        'plugins.updateFailed': '无法更新 MCP Server，请重试。',
        'plugins.reconnectFailed': '无法重连 MCP Server，请重试。',
        'plugins.saveFailed': '无法保存 MCP 配置，请检查字段后重试。',
        'plugins.loadFailed': '无法加载 MCP 配置，请重试。',
        'plugins.testFailed': 'MCP 测试失败，请检查服务配置后重试。',
        'plugins.loadSkillsFailed': '无法加载 Skills，请重试。',
        'plugins.notConfigured': '待配置',
        'plugins.connecting': '连接中',
        'plugins.error': '异常',

        'chat.workspaceEmpty': '当前未附加文件',
        'chat.stop': '停止生成',
        'chat.send': '发送消息',
        'chat.placeholder': '在这里输入您的问题或请求...',
        'chat.you': '您',
        'chat.agent': '助手',
        'chat.needsClarification': '需要你的澄清',
        'chat.inputAnswer': '输入你的回答...',
        'chat.submitting': '提交中...',
        'chat.submit': '提交',
        'chat.steerHint': '思考中补充说明会作为 steer/follow-up 发送',
        'chat.status': '状态',
        'chat.stopped': '已停止',
        'chat.uploadTooltip': '上传并附加文件',
        'chat.attachedFiles': '已附加的文件',
        'chat.removeAttachment': '移除 {name}',
        'chat.steerPlaceholder': '思考中补充说明...',
        'chat.startMessage': '发送一条消息开始会话...',
        'chat.pageTitle': 'Agent 对话',
        'chat.agents': 'Agents',
        'chat.details': '详细信息',
        'chat.resizeWidth': '使用方向键调整对话区域宽度',
        'chat.openDetails': '打开详细信息',
        'chat.closeDetails': '关闭详细信息',
        'chat.clarificationTitle': '需要你的澄清',
        'chat.clarificationOptions': '候选回答',
        'chat.clarificationEditHint': '选择一个选项后可修改，或直接输入你的回答...',
        'chat.requestFailed': '请求未能完成。',
        'chat.retryHint': '请检查网络或配置后重试。',
        'chat.uploadFailed': '文件上传失败，请检查文件后重试。',
        'chat.toolCalling': '调用工具：{name}',
        'chat.toolCompleted': '完成工具：{name}',
        'chat.toolFailed': '工具失败：{name}',
        'chat.skillActivated': 'Skill 已激活：{name}',
        'chat.skillLoaded': '已加载：{name}',
        'chat.streamReconnecting': '连接中断，正在重连…',
        'chat.subagentLine': 'subagent：{name}  工具：{tool}/{count}  用时：{elapsed}  产物：{output}',
        'chat.subagentOutputPending': '待输出',
        'chat.subagentOutputProduced': '已输出',
        'chat.subagentOutputNone': '未输出（{status}）',
        'chat.subagentStatus.running': '运行中',
        'chat.subagentStatus.completed': '无报告',
        'chat.subagentStatus.failed': '失败',
        'chat.subagentStatus.cancelled': '已取消',
        'chat.subagentStatus.interrupted': '已中断',
        'chat.subagentStatus.timed_out': '超时',
        'chat.subagentStatus.budget_exhausted': '预算耗尽',
        'chat.subagentStatus.invalid_output': '报告无效',
        'chat.subagentStatus.abort_unconfirmed': '中止未确认',
        'chat.phaseValidatingSql': '校验 SQL',
        'chat.phaseRunningQuery': '执行查询',
        'chat.phaseRunningTool': '运行工具',
        'chat.phaseDoneTool': '完成工具',
        'chat.phaseErrorTool': '工具失败',
        'chat.retryNotice': '重试 {operation}：{attempt}/{max}，{delay}s 后继续',
        'chat.semanticWaiting': '语义上下文仍在准备中，你可以继续处理其他问题。',
        
        'tools.processing': '思考中...',
        'tools.statusError': '错误',
        'tools.statusDone': '完成',
        'tools.statusRunning': '思考中',
        'tools.args': '工具参数',
        'tools.result': '工具结果',
        'tools.details': '详细信息',
        'tools.copy': '复制',
        'tools.noCalls': '暂无工具调用',
        'tools.noCallsHint': 'Agent 执行工具后，详细信息会显示在这里。',

        'widgets.true': '是',
        'widgets.false': '否',
        'widgets.legacyEcharts': '此图表来自早期版本，已不再绘制。请重新提问，以基于已发布数据重建图表。',
        'widgets.metric': '指标',
        'widgets.column': '列',
        'widgets.dataPoint': '数据点',
        'widgets.step': '步骤',
        'widgets.preview': '查看',
        'widgets.download': '下载',
        'widgets.renderFail': '组件渲染失败',

        'preview.title': '文件预览',
        'preview.file': '文件',
        'preview.close': '关闭预览',
        'preview.openExternal': '在浏览器中打开',
        'preview.unsupported': '当前文件类型暂不支持内联预览。',
        'preview.loading': '正在加载预览…',
        'preview.loadError': '无法加载预览，请检查后端服务或文件权限。',
        'preview.csvColumn': '列 {number}',
        'preview.csvLimit': '仅显示前 200 行',
        'preview.resize': '调整预览窗口大小',
        'editor.edit': '编辑文件',
        'editor.save': '保存文件',
        'editor.close': '关闭文件编辑器',
        'editor.loading': '正在加载文件…',
        'editor.loadFailed': '无法加载文件，请稍后重试。',
        'editor.saveFailed': '无法保存文件，请检查连接后重试。',
        'semantic.close': '关闭语义资产',
        'semantic.loading': '正在加载语义资产…',
        'semantic.loadFailed': '无法加载语义资产，请稍后重试。',

        'onboarding.badge': '桌面端初始化',
        'onboarding.titleLine1': '连接 Data Agent',
        'onboarding.titleLine2': '到你的模型供应商',
        'onboarding.description': '先选择界面语言，再配置一个可用的模型供应商，本地助手就能立即开始工作。',
        'onboarding.featureLabel': '本次引导会完成',
        'onboarding.featureOne': '使用 Electron safeStorage 加密并保存桌面端密钥',
        'onboarding.featureTwo': '在同一个流程中完成模型和数据库的初始配置',
        'onboarding.featureThree': '在进入主界面前就确定默认语言，后续自动沿用',
        'onboarding.browserWarning': '当前为浏览器开发模式。密钥会发送到后端供本次会话使用，但不会持久化保存到 localStorage。',
        'onboarding.formEyebrow': '首次启动',
        'onboarding.formTitle': '完成首次使用配置',
        'onboarding.formDescription': '先确认界面语言，再选择 Data Agent 要连接的模型供应商和默认模型。',
        'onboarding.languageLabel': '界面语言',
        'onboarding.languageHint': '当前选择会保存下来，下次打开桌面端时继续沿用。',
        'onboarding.language.zh': '中文',
        'onboarding.language.en': 'English',
        'onboarding.providerAria': '模型供应商',
        'onboarding.provider.openai': 'OpenAI 兼容',
        'onboarding.provider.anthropic': 'Anthropic',
        'onboarding.apiKey': 'API 密钥',
        'onboarding.baseUrl': '基础地址',
        'onboarding.defaultModel': '默认模型',
        'onboarding.optionalMySql': '可选 MySQL 连接',
        'onboarding.host': '主机',
        'onboarding.port': '端口',
        'onboarding.user': '用户名',
        'onboarding.password': '密码',
        'onboarding.databaseName': '数据库名称',
        'onboarding.verify': '校验并启动',
        'onboarding.verifying': '校验中...',
        'onboarding.errorMissingKey': '继续之前请至少填写一个 API 密钥。',
        'onboarding.errorVerify': '模型配置校验失败',
        'onboarding.errorSave': '保存配置失败',

        'task.new': '新任务',
        'task.created': '新任务创建成功',
        'task.emptyPrompt': '请先创建任务。',
        'task.confirmDelete': '确认删除任务“{name}”及其全部会话吗？',
        'session.new': '新会话',
        'session.create': '新建会话',
        'session.empty': '暂无会话',
        'session.emptyPrompt': '当前任务暂无会话，需要开始对话时再新建会话。',
        'session.confirmDelete': '确认删除会话“{name}”吗？',
        'knowledge.loadFailed': '加载知识库失败',

        'semantic.toolbarLabel': '语义资产视图模式',
        'semantic.split': '对照',
        'semantic.code': '代码',
        'semantic.visual': '可视化',
        'semantic.narrowHint': '窄屏已切换为单栏标签页',
        'semantic.manifestOnly': '此模型由系统 manifest 定义',
        'semantic.manifestOnlyDesc': '暂无独立 YAML 文件。如需自定义，请通过 KTX 创建 Overlay。',
        'semantic.yamlSource': 'YAML 原文',
        'semantic.businessKnowledge': '业务知识 YAML',
        'semantic.queryable': '可查询',
        'semantic.noPhysicalSource': '未声明物理来源',
        'semantic.defaultTime': '默认时间：',
        'semantic.tags': '标签',
        'semantic.copy': '复制源码',
        'semantic.copied': '已复制',
        'semantic.noFields': '未定义字段',
        'semantic.fields': '字段',
        'semantic.inheritedFromManifest': '继承自 manifest'
    }
};

interface LanguageContextProps {
    language: Language;
    toggleLanguage: () => void;
    setLanguage: (language: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const getInitialLanguage = (): Language => {
    if (typeof window === 'undefined') return 'zh';
    const savedLang = localStorage.getItem('app_language') as Language;
    return savedLang === 'en' || savedLang === 'zh' ? savedLang : 'zh';
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(getInitialLanguage);

    useEffect(() => {
        document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en';
        document.documentElement.dir = 'ltr';
    }, [language]);

    const toggleLanguage = useCallback(() => {
        const nextLang = language === 'zh' ? 'en' : 'zh';
        setLanguage(nextLang);
        localStorage.setItem('app_language', nextLang);
    }, [language]);

    const updateLanguage = useCallback((nextLanguage: Language) => {
        setLanguage(nextLanguage);
        localStorage.setItem('app_language', nextLanguage);
    }, []);

    const t = useCallback((key: string): string => {
        return translations[language][key] || key;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage: updateLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

const defaultLanguageContext: LanguageContextProps = {
    language: 'zh',
    toggleLanguage: () => {},
    setLanguage: () => {},
    t: (key: string) => translations.zh[key] || translations.en[key] || key,
};

export const useLanguage = (): LanguageContextProps => {
    const context = useContext(LanguageContext);
    return context || defaultLanguageContext;
};
