import React, { createContext, useCallback, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'zh';

interface Translations {
    [key: string]: {
        [key: string]: string;
    };
}

// Translations dictionary
const translations: Translations = {
    en: {
        'sidebar.newWorkspace': 'New Workspace',
        'sidebar.chat': 'Chat',
        'sidebar.knowledge': 'Knowledge',
        'sidebar.workspace': 'Workspace Files',
        'sidebar.history': 'Workspace History',
        'sidebar.plugins': 'Plugins',
        'sidebar.metrics': 'Metrics',
        'sidebar.settings': 'Settings',
        'sidebar.langToggle': '切换至中文',

        'app.preparing': 'Preparing Data Agent...',

        'auth.registerSubtitle': 'Create the first admin account',
        'auth.loginSubtitle': 'Sign in to continue',
        'auth.username': 'Username',
        'auth.password': 'Password',
        'auth.createAccount': 'Create account',
        'auth.signIn': 'Sign in',
        'auth.submitting': 'Please wait',
        'auth.useExisting': 'Use an existing account',
        'auth.createFirst': 'Create first account',
        'auth.errorFallback': 'Authentication failed',

        'landing.nav.capabilities': 'Capabilities',
        'landing.nav.workflow': 'Workflow',
        'landing.nav.security': 'Security',
        'landing.nav.highlights': 'Design',
        'landing.nav.login': 'Sign in',
        'landing.kicker': 'Desktop agent product for data analysts',
        'landing.hero.title': 'anytime,anywhere,it`s yourDB。',
        'landing.hero.subtitle': 'yourDB是一款专为数据分析人员设计的桌面agent产品。',
        'landing.hero.primary': 'Start with YourDB',
        'landing.hero.secondary': 'Explore what it can do',
        'landing.trust.local': 'Local workspace',
        'landing.trust.mcp': 'MCP tools',
        'landing.trust.database': 'Database aware',
        'landing.trust.skills': 'Custom skills',
        'landing.visual.label': 'YourDB product preview',
        'landing.visual.workspace': 'New workspace',
        'landing.visual.history': 'History',
        'landing.visual.files': 'Workspace files',
        'landing.visual.prompt': 'Analyze monthly sales and build a dashboard.',
        'landing.visual.metricOne': 'Revenue +18%',
        'landing.visual.metricTwo': 'Top region East',
        'landing.visual.metricThree': 'Export ready',
        'landing.visual.placeholderTitle': 'Product image',
        'landing.visual.placeholder': 'Image placeholder',
        'landing.visual.placeholderDesc': 'The product screenshot or generated visual can be placed here later.',
        'landing.capabilities.eyebrow': 'What YourDB can do',
        'landing.capabilities.title': 'From raw tables to finished work',
        'landing.capabilities.desc': 'Describe the outcome. YourDB plans the steps, calls the right tools, and returns artifacts you can inspect and reuse.',
        'landing.capability.data.title': 'Query databases',
        'landing.capability.data.desc': 'Connect MySQL and MCP services, inspect schema context, and run guarded analysis workflows.',
        'landing.capability.sheets.title': 'Generate spreadsheets',
        'landing.capability.sheets.desc': 'Turn messy data into structured Excel files with formulas, summaries, and export-ready formatting.',
        'landing.capability.dashboard.title': 'HTML dashboards',
        'landing.capability.dashboard.desc': 'Generate standalone HTML dashboards with interactive charts, metrics, and drill-down views.',
        'landing.capability.docs.title': 'Produce reports',
        'landing.capability.docs.desc': 'Write analysis summaries, explain findings, and package outputs into files inside the session workspace.',
        'landing.capability.query.title': 'Data queries',
        'landing.capability.query.desc': 'Connect databases and MCP tools, understand schema and business context, and complete verifiable queries in natural language.',
        'landing.capability.query.caption': 'Data query image placeholder',
        'landing.capability.export.title': 'Report export',
        'landing.capability.export.desc': 'Turn analysis steps and results into deliverable files with tables, summaries, conclusions, and managed export paths.',
        'landing.capability.export.caption': 'Report export image placeholder',
        'landing.capability.dashboard.caption': 'HTML dashboard image placeholder',
        'landing.capability.report.title': 'Analysis reports',
        'landing.capability.report.desc': 'Organize metrics, conclusions, and explanations around business questions, then save reports into the workspace.',
        'landing.capability.report.caption': 'Analysis report image placeholder',
        'landing.highlights.eyebrow': 'yourDB design highlights',
        'landing.highlights.title': 'Designed around reliable data-agent work',
        'landing.highlights.desc': 'yourDB is not just a chat box. It organizes context, execution, tools, and local files around the way analysts actually work.',
        'landing.highlight.context.title': 'Six-layer context organization',
        'landing.highlight.context.desc': 'System prompt, database metadata, knowledge, skills, files, and chat history are organized as layered context.',
        'landing.highlight.redirect.title': 'Interactive redirection',
        'landing.highlight.redirect.desc': 'The agent can redirect follow-up interactions into the right clarification, drill-down, or workspace action.',
        'landing.highlight.sql.title': 'SQL safety lock',
        'landing.highlight.sql.desc': 'Query execution is guarded by SQL safety checks, dry-run validation, and controlled tool paths.',
        'landing.highlight.mcp.title': 'MCP integration',
        'landing.highlight.mcp.desc': 'Connect databases and external capabilities through MCP while keeping the agent workflow unified.',
        'landing.highlight.skill.title': 'Skill support',
        'landing.highlight.skill.desc': 'Project and global skills can extend the agent with specialized workflows and reusable procedures.',
        'landing.highlight.local.title': 'Local runtime',
        'landing.highlight.local.desc': 'Run the product locally with session workspaces, local artifacts, and desktop-friendly storage.',
        'landing.security.eyebrow': 'Built for controlled execution',
        'landing.security.title': 'Keep data work traceable and contained',
        'landing.security.desc': 'YourDB separates work by session, stores chat history in the app database, and keeps generated files in the local workspace.',
        'landing.security.itemOne': 'Session-level workspace isolation',
        'landing.security.itemTwo': 'Login-protected history and files',
        'landing.security.itemThree': 'MCP integrations for controlled external tools',
        'landing.workflow.eyebrow': 'How it works',
        'landing.workflow.title': 'A focused loop for data tasks',
        'landing.workflow.desc': 'Ask, execute, verify, and continue without switching between scripts, spreadsheets, dashboards, and chat history.',
        'landing.workflow.ask.title': 'Ask in natural language',
        'landing.workflow.ask.desc': 'Describe the business question, attached files, or database context in plain language.',
        'landing.workflow.execute.title': 'Let the agent run tools',
        'landing.workflow.execute.desc': 'YourDB plans queries, calls configured tools, and streams progress while preserving context.',
        'landing.workflow.deliver.title': 'Review finished artifacts',
        'landing.workflow.deliver.desc': 'Inspect charts, tables, reports, and workspace files, then continue the same session.',
        'landing.cta.eyebrow': 'Get started',
        'landing.cta.title': 'Open your secure workspace',
        'landing.cta.desc': 'Create the first admin account or sign in to continue with your saved sessions and database context.',
        'landing.faq.eyebrow': 'FAQ',
        'landing.faq.title': 'Common questions',
        'landing.faq.one.q': 'Is this a desktop or web product?',
        'landing.faq.one.a': 'YourDB is designed as a local workspace with a web UI and desktop packaging support.',
        'landing.faq.two.q': 'Where is chat history stored?',
        'landing.faq.two.a': 'Chat sessions are stored in the application database and tied to the authenticated user.',
        'landing.faq.three.q': 'Can it connect to external tools?',
        'landing.faq.three.a': 'Yes. YourDB uses MCP integrations and local providers to connect database, knowledge, and workflow tools.',

        'settings.title': 'Settings',
        'settings.model': 'Model',
        'settings.database': 'Database',
        'settings.modelSettings': 'Model Settings',
        'settings.providers': 'Providers',
        'settings.defaultModelTitle': 'Default Model and Provider',
        'settings.defaultModelSubtitle': 'Agent Working Model',
        'settings.defaultModelHint': 'Tip: To change the working model, select the provider on the left, enable it, and select the desired model.',
        'settings.historyLimitTitle': 'Chat History Limit',
        'settings.maxTurns': 'Max Dialogue Turns',
        'settings.maxTurnsSubtitle': 'Number of retained turns (0 = unlimited)',
        'settings.maxTokens': 'Max History Tokens',
        'settings.maxTokensSubtitle': 'Max retained tokens (0 = unlimited)',
        'settings.apiKeyTitle': 'API Key',
        'settings.apiKeyPlaceholder': 'To keep current, enter [configured]',
        'settings.supportModels': 'Supported Models',
        'settings.refreshModels': 'Refresh Available Models from API',
        'settings.howToGetToken': 'How to get an API Token?',
        'settings.enableProvider': 'Enable this provider to use its models in chat',
        'settings.save': 'Save Settings',
        'settings.dbSettings': 'MySQL Database Configuration',
        'settings.dbHost': 'Host',
        'settings.dbPort': 'Port',
        'settings.dbUser': 'Username',
        'settings.dbPassword': 'Password',
        'settings.dbPasswordPlaceholder': 'Enter password or leave blank if no auth',
        'settings.dbDatabase': 'Database Name',
        'settings.dbTest': 'Test Connection',
        'settings.testing': 'Testing...',
        'settings.enabled': 'Enabled (Current Worker)',
        'settings.disabled': 'Disabled',

        'plugins.mcp': 'MCP Settings',
        'plugins.skills': 'Skills Settings',
        'plugins.installed': 'Installed',
        'plugins.addNew': 'Install New',
        'plugins.status': 'Status',
        'plugins.connected': 'Connected',
        'plugins.disconnected': 'Disconnected',
        'plugins.toolsNum': 'Total Tools',
        'plugins.addNewServer': 'Add New MCP Server',
        'plugins.installLabel': 'Install via Command / Package',
        'plugins.installPlaceholder': 'e.g., npx -y @server/foo',
        'plugins.envLabel': 'Environment Variables (JSON)',
        'plugins.envPlaceholder': '{"TOKEN": "abc"} (Optional)',
        'plugins.serverName': 'Server Identifier',
        'plugins.installing': 'Installing...',
        'plugins.install': 'Install',
        'plugins.noServers': 'No MCP servers configured',
        'plugins.settings': 'Settings',
        'plugins.mcpDesc': 'Manage MCP Server configurations, connection states, and bridge tools.',
        'plugins.refresh': 'Refresh',
        'plugins.add': 'Add',
        'plugins.disabled': 'Disabled',
        'plugins.noDesc': 'No description',
        'plugins.edit': 'Edit',
        'plugins.noSrvHint': 'No MCP server yet, click "Add" on the top right.',
        'plugins.unnamedSrv': 'Unnamed server',
        'plugins.selectHint': 'Please select an MCP server from the left to edit.',
        'plugins.searchSkill': 'Search Skill',
        'plugins.noSkills': 'No Skills',
        'plugins.loadingSkills': 'Loading Skills...',

        'chat.workspaceEmpty': 'No files attached.',
        'chat.clearChat': 'Clear Chat',
        'chat.stop': 'Stop',
        'chat.send': 'Send',
        'chat.placeholder': 'Enter your request or question here...',
        'chat.you': 'You',
        'chat.agent': 'Agent',
        'chat.needsClarification': 'Needs your clarification',
        'chat.inputAnswer': 'Enter your answer...',
        'chat.submitting': 'Submitting...',
        'chat.submit': 'Submit',
        'chat.steerHint': 'Additional instructions will be sent as steer/follow-up',
        'chat.attachHint': 'Select files in Workspace to attach to this query',
        'chat.status': 'Status',
        'chat.stopped': 'Stopped',
        'chat.uploadTooltip': 'Upload to workspace',
        'chat.steerPlaceholder': 'Steering instructions...',
        'chat.startMessage': 'Send a message to start...',
        
        'tools.processing': 'Thinking...',
        'tools.statusError': 'Error',
        'tools.statusDone': 'Done',
        'tools.statusRunning': 'Thinking',
        'tools.args': 'Arguments',
        'tools.result': 'Result',
        'tools.details': 'Details',
        'tools.copy': 'Copy',
        'tools.noCalls': 'No tool calls yet',

        'widgets.true': 'Yes',
        'widgets.false': 'No',
        'widgets.metric': 'Metric',
        'widgets.column': 'Column',
        'widgets.dataPoint': 'Data Point',
        'widgets.step': 'Step',
        'widgets.preview': 'Preview',
        'widgets.download': 'Download',
        'widgets.renderFail': 'Widget render failed',

        'preview.title': 'File preview',
        'preview.file': 'File',
        'preview.close': 'Close preview',
        'preview.openExternal': 'Open in browser',
        'preview.unsupported': 'This file type does not support inline preview yet.',

        'onboarding.badge': 'Desktop Setup',
        'onboarding.titleLine1': 'Connect Data Agent',
        'onboarding.titleLine2': 'to your model provider',
        'onboarding.description': 'Choose your language, connect one model provider, and you can start using the local assistant right away.',
        'onboarding.featureLabel': 'What this setup does',
        'onboarding.featureOne': 'Encrypts desktop secrets with Electron safeStorage before reuse',
        'onboarding.featureTwo': 'Keeps provider and database settings together in one startup flow',
        'onboarding.featureThree': 'Lets you switch the interface language before entering the app',
        'onboarding.browserWarning': 'Browser dev mode detected. Keys will be sent to the backend for this session, but they will not be persisted in localStorage.',
        'onboarding.formEyebrow': 'Getting Started',
        'onboarding.formTitle': 'Finish the first-run configuration',
        'onboarding.formDescription': 'Set your preferred language first, then choose the provider you want Data Agent to use.',
        'onboarding.languageLabel': 'Interface language',
        'onboarding.languageHint': 'This choice is saved and reused the next time you open the desktop app.',
        'onboarding.language.zh': 'Chinese',
        'onboarding.language.en': 'English',
        'onboarding.providerAria': 'Model provider',
        'onboarding.provider.openai': 'OpenAI compatible',
        'onboarding.provider.anthropic': 'Anthropic',
        'onboarding.apiKey': 'API key',
        'onboarding.baseUrl': 'Base URL',
        'onboarding.defaultModel': 'Default model',
        'onboarding.optionalMySql': 'Optional MySQL connection',
        'onboarding.host': 'Host',
        'onboarding.port': 'Port',
        'onboarding.user': 'User',
        'onboarding.password': 'Password',
        'onboarding.databaseName': 'Database name',
        'onboarding.verify': 'Verify and start',
        'onboarding.verifying': 'Verifying...',
        'onboarding.errorMissingKey': 'Please enter at least one API key before continuing.',
        'onboarding.errorVerify': 'LLM verification failed',
        'onboarding.errorSave': 'Failed to save configuration',

        'session.newWorkspace': 'New Workspace',
        'session.workspacePrefix': 'Workspace'
    },
    zh: {
        'sidebar.newWorkspace': '新建工作区',
        'sidebar.chat': '对话',
        'sidebar.knowledge': '知识库',
        'sidebar.workspace': '工作区文件',
        'sidebar.history': '历史工作区',
        'sidebar.plugins': '插件管理',
        'sidebar.metrics': '指标',
        'sidebar.settings': '设置',
        'sidebar.langToggle': 'Switch to English',

        'app.preparing': '正在准备 Data Agent...',

        'auth.registerSubtitle': '创建首个管理员账号',
        'auth.loginSubtitle': '登录后继续',
        'auth.username': '用户名',
        'auth.password': '密码',
        'auth.createAccount': '创建账号',
        'auth.signIn': '登录',
        'auth.submitting': '请稍候',
        'auth.useExisting': '使用已有账号',
        'auth.createFirst': '创建首个账号',
        'auth.errorFallback': '认证失败',

        'landing.nav.capabilities': '能力',
        'landing.nav.workflow': '流程',
        'landing.nav.security': '安全',
        'landing.nav.highlights': '设计亮点',
        'landing.nav.login': '登录',
        'landing.kicker': '专为数据分析人员设计的桌面 Agent 产品',
        'landing.hero.title': 'anytime,anywhere,it`s yourDB。',
        'landing.hero.subtitle': 'yourDB是一款专为数据分析人员设计的桌面agent产品。',
        'landing.hero.primary': '开始使用 YourDB',
        'landing.hero.secondary': '查看核心能力',
        'landing.trust.local': '本地工作区',
        'landing.trust.mcp': 'MCP 工具',
        'landing.trust.database': '理解数据库',
        'landing.trust.skills': '自定义技能',
        'landing.visual.label': 'YourDB 产品预览',
        'landing.visual.workspace': '新建工作区',
        'landing.visual.history': '历史记录',
        'landing.visual.files': '工作区文件',
        'landing.visual.prompt': '分析月度销售并生成一个看板。',
        'landing.visual.metricOne': '收入 +18%',
        'landing.visual.metricTwo': '华东领先',
        'landing.visual.metricThree': '可导出',
        'landing.visual.placeholderTitle': '产品图片',
        'landing.visual.placeholder': '图片占位符',
        'landing.visual.placeholderDesc': '后续可在这里替换为产品截图或生成的主视觉图片。',
        'landing.capabilities.eyebrow': 'YourDB 能做什么',
        'landing.capabilities.title': '从原始数据到可交付成果',
        'landing.capabilities.desc': '描述你想要的结果。YourDB 会规划步骤、调用合适工具，并返回可检查、可复用的工作产物。',
        'landing.capability.data.title': '查询数据库',
        'landing.capability.data.desc': '连接 MySQL 和 MCP 服务，理解表结构上下文，并执行受控的数据分析流程。',
        'landing.capability.sheets.title': '生成表格',
        'landing.capability.sheets.desc': '把混乱数据整理成带公式、汇总和规范格式的 Excel 文件。',
        'landing.capability.dashboard.title': 'HTML 看板',
        'landing.capability.dashboard.desc': '生成可独立打开的 HTML 看板，包含交互图表、关键指标和下钻视图。',
        'landing.capability.docs.title': '输出分析报告',
        'landing.capability.docs.desc': '撰写分析结论、解释发现，并把结果沉淀到当前会话工作区。',
        'landing.capability.query.title': '数据查询',
        'landing.capability.query.desc': '连接数据库与 MCP 工具，理解表结构和业务上下文，用自然语言完成可验证的数据查询。',
        'landing.capability.query.caption': '数据查询图片占位符',
        'landing.capability.export.title': '报告导出',
        'landing.capability.export.desc': '把分析过程和结果沉淀为可交付文件，支持表格、摘要、结论和导出路径管理。',
        'landing.capability.export.caption': '报告导出图片占位符',
        'landing.capability.dashboard.caption': 'HTML 看板图片占位符',
        'landing.capability.report.title': '分析报告',
        'landing.capability.report.desc': '围绕业务问题组织指标、结论和解释，生成清晰的分析报告并保存在工作区中。',
        'landing.capability.report.caption': '分析报告图片占位符',
        'landing.highlights.eyebrow': 'yourDB 设计亮点',
        'landing.highlights.title': '围绕可靠的数据 Agent 工作流设计',
        'landing.highlights.desc': 'yourDB 不只是一个聊天框，而是围绕分析师真实工作方式组织上下文、执行、工具和本地文件。',
        'landing.highlight.context.title': '六层上下文组织',
        'landing.highlight.context.desc': '系统提示词、数据库元数据、知识库、技能、文件和聊天历史按层组织，减少上下文混乱。',
        'landing.highlight.redirect.title': '交互重定向',
        'landing.highlight.redirect.desc': '把追问、澄清、下钻和工作区操作重定向到正确流程，让对话持续推进任务。',
        'landing.highlight.sql.title': 'SQL 安全锁',
        'landing.highlight.sql.desc': '通过 SQL 安全检查、空跑验证和受控工具路径降低误操作风险。',
        'landing.highlight.mcp.title': 'MCP 集成',
        'landing.highlight.mcp.desc': '通过 MCP 连接数据库和外部能力，同时保持统一的 Agent 工作流。',
        'landing.highlight.skill.title': 'Skill 支持',
        'landing.highlight.skill.desc': '项目级和全局 Skill 可以扩展专用工作流，把经验沉淀为可复用能力。',
        'landing.highlight.local.title': '本地运行',
        'landing.highlight.local.desc': '支持本地运行、会话工作区、本地文件产物和桌面端友好的存储方式。',
        'landing.security.eyebrow': '为可控执行而设计',
        'landing.security.title': '让数据工作可追踪、可隔离',
        'landing.security.desc': 'YourDB 按会话隔离工作区，把聊天历史保存到应用数据库，并将生成文件留在本地工作区。',
        'landing.security.itemOne': 'Session 级工作区隔离',
        'landing.security.itemTwo': '登录保护历史和文件',
        'landing.security.itemThree': '通过 MCP 受控连接外部工具',
        'landing.workflow.eyebrow': '使用方式',
        'landing.workflow.title': '围绕数据任务的闭环',
        'landing.workflow.desc': '提问、执行、验证、继续追问，不需要在脚本、表格、看板和聊天历史之间来回切换。',
        'landing.workflow.ask.title': '自然语言提问',
        'landing.workflow.ask.desc': '用日常语言描述业务问题、附加文件或数据库上下文。',
        'landing.workflow.execute.title': 'Agent 调用工具执行',
        'landing.workflow.execute.desc': 'YourDB 规划查询、调用已配置工具，并在保留上下文的同时流式展示进度。',
        'landing.workflow.deliver.title': '检查交付产物',
        'landing.workflow.deliver.desc': '查看图表、表格、报告和工作区文件，再基于同一个会话继续分析。',
        'landing.cta.eyebrow': '开始使用',
        'landing.cta.title': '进入你的安全工作区',
        'landing.cta.desc': '创建首个管理员账号，或登录继续使用已保存的会话和数据库上下文。',
        'landing.faq.eyebrow': '常见问题',
        'landing.faq.title': '你可能想知道',
        'landing.faq.one.q': '这是桌面产品还是 Web 产品？',
        'landing.faq.one.a': 'YourDB 面向本地工作区设计，提供 Web UI，并支持桌面端打包。',
        'landing.faq.two.q': '聊天历史保存在哪里？',
        'landing.faq.two.a': '聊天会话保存在应用数据库中，并与登录用户绑定。',
        'landing.faq.three.q': '可以连接外部工具吗？',
        'landing.faq.three.a': '可以。YourDB 通过 MCP 集成和本地工具连接数据库、知识库和工作流能力。',

        'settings.title': '系统设置',
        'settings.model': '模型',
        'settings.database': '数据库',
        'settings.modelSettings': '模型设置',
        'settings.providers': '供应商',
        'settings.defaultModelTitle': '配置默认模型和供应商',
        'settings.defaultModelSubtitle': 'Agent 工作模型',
        'settings.defaultModelHint': '提示：要更改工作模型，请在左侧选择对应的供应商，然后开启供应商并选择所需模型。',
        'settings.historyLimitTitle': '对话历史限制',
        'settings.maxTurns': '最大对话轮次',
        'settings.maxTurnsSubtitle': '保留的对话轮次数量（0 = 不限制）',
        'settings.maxTokens': '最大历史 Token 数',
        'settings.maxTokensSubtitle': '对话中的最大 Token 数量（0 = 不限制）',
        'settings.apiKeyTitle': 'API 密钥',
        'settings.apiKeyPlaceholder': '留空表示不修改，如有请填写',
        'settings.supportModels': '支持的模型',
        'settings.refreshModels': '刷新模型列表',
        'settings.howToGetToken': '如何获取 API 令牌？',
        'settings.enableProvider': '开启此供应商以在聊天时使用其模型',
        'settings.save': '保存设置',
        'settings.dbSettings': 'MySQL 数据库配置',
        'settings.dbHost': '主机地址',
        'settings.dbPort': '端口',
        'settings.dbUser': '用户名',
        'settings.dbPassword': '密码',
        'settings.dbPasswordPlaceholder': '输入密码，若无请留空',
        'settings.dbDatabase': '数据库名称',
        'settings.dbTest': '测试连接',
        'settings.testing': '测试中...',
        'settings.enabled': '已启用 (当前工作平台)',
        'settings.disabled': '已停用',

        'plugins.mcp': 'MCP 设置',
        'plugins.skills': 'Skills 设置',
        'plugins.installed': '已安装',
        'plugins.addNew': '安装新插件',
        'plugins.status': '状态',
        'plugins.connected': '已连接',
        'plugins.disconnected': '未连接',
        'plugins.toolsNum': '工具数量',
        'plugins.addNewServer': '添加新 MCP 服务',
        'plugins.installLabel': '运行命令 / 包名',
        'plugins.installPlaceholder': '例：npx -y @server/foo',
        'plugins.envLabel': '环境变量 (JSON格式)',
        'plugins.envPlaceholder': '{"KEY": "value"}（可选）',
        'plugins.serverName': '服务标识符',
        'plugins.installing': '安装中...',
        'plugins.install': '安装',
        'plugins.noServers': '暂无 MCP 服务器配置',
        'plugins.settings': '设置',
        'plugins.mcpDesc': '管理 MCP Server 配置、连接状态与桥接工具。',
        'plugins.refresh': '刷新',
        'plugins.add': '添加',
        'plugins.disabled': '已禁用',
        'plugins.noDesc': '暂无描述',
        'plugins.edit': '编辑',
        'plugins.noSrvHint': '还没有 MCP server，点击右上角“添加”。',
        'plugins.unnamedSrv': '未命名 server',
        'plugins.selectHint': '请选择左侧的 MCP server 进行编辑。',
        'plugins.searchSkill': '搜索 Skill',
        'plugins.noSkills': '暂无 Skills',
        'plugins.loadingSkills': '正在加载 Skills...',

        'chat.workspaceEmpty': '当前未附加工作区文件',
        'chat.clearChat': '清空对话',
        'chat.stop': '停止生成',
        'chat.send': '发送消息',
        'chat.placeholder': '在这里输入您的问题或请求...',
        'chat.you': '您',
        'chat.agent': '助手',
        'chat.needsClarification': '需要你的澄清',
        'chat.inputAnswer': '输入你的回答...',
        'chat.submitting': '提交中...',
        'chat.submit': '提交',
        'chat.steerHint': '思考中补充说明会作为 steer/follow-up 发送',
        'chat.attachHint': '可在左侧 Workspace 勾选文件后附加到本次提问',
        'chat.status': '状态',
        'chat.stopped': '已停止',
        'chat.uploadTooltip': '上传到当前会话工作区',
        'chat.steerPlaceholder': '思考中补充说明...',
        'chat.startMessage': '发送一条消息开始会话...',
        
        'tools.processing': '思考中...',
        'tools.statusError': '错误',
        'tools.statusDone': '完成',
        'tools.statusRunning': '思考中',
        'tools.args': '工具参数',
        'tools.result': '工具结果',
        'tools.details': '详细信息',
        'tools.copy': '复制',
        'tools.noCalls': '暂无工具调用',

        'widgets.true': '是',
        'widgets.false': '否',
        'widgets.metric': '指标',
        'widgets.column': '列',
        'widgets.dataPoint': '数据点',
        'widgets.step': '步骤',
        'widgets.preview': '查看',
        'widgets.download': '下载',
        'widgets.renderFail': '组件渲染失败',

        'preview.title': '文件预览',
        'preview.file': '文件',
        'preview.close': '关闭预览',
        'preview.openExternal': '在浏览器中打开',
        'preview.unsupported': '当前文件类型暂不支持内联预览。',

        'onboarding.badge': '桌面端初始化',
        'onboarding.titleLine1': '连接 Data Agent',
        'onboarding.titleLine2': '到你的模型供应商',
        'onboarding.description': '先选择界面语言，再配置一个可用的模型供应商，本地助手就能立即开始工作。',
        'onboarding.featureLabel': '本次引导会完成',
        'onboarding.featureOne': '使用 Electron safeStorage 加密并保存桌面端密钥',
        'onboarding.featureTwo': '在同一个流程中完成模型和数据库的初始配置',
        'onboarding.featureThree': '在进入主界面前就确定默认语言，后续自动沿用',
        'onboarding.browserWarning': '当前为浏览器开发模式。密钥会发送到后端供本次会话使用，但不会持久化保存到 localStorage。',
        'onboarding.formEyebrow': '首次启动',
        'onboarding.formTitle': '完成首次使用配置',
        'onboarding.formDescription': '先确认界面语言，再选择 Data Agent 要连接的模型供应商和默认模型。',
        'onboarding.languageLabel': '界面语言',
        'onboarding.languageHint': '当前选择会保存下来，下次打开桌面端时继续沿用。',
        'onboarding.language.zh': '中文',
        'onboarding.language.en': 'English',
        'onboarding.providerAria': '模型供应商',
        'onboarding.provider.openai': 'OpenAI 兼容',
        'onboarding.provider.anthropic': 'Anthropic',
        'onboarding.apiKey': 'API 密钥',
        'onboarding.baseUrl': '基础地址',
        'onboarding.defaultModel': '默认模型',
        'onboarding.optionalMySql': '可选 MySQL 连接',
        'onboarding.host': '主机',
        'onboarding.port': '端口',
        'onboarding.user': '用户名',
        'onboarding.password': '密码',
        'onboarding.databaseName': '数据库名称',
        'onboarding.verify': '校验并启动',
        'onboarding.verifying': '校验中...',
        'onboarding.errorMissingKey': '继续之前请至少填写一个 API 密钥。',
        'onboarding.errorVerify': '模型配置校验失败',
        'onboarding.errorSave': '保存配置失败',

        'session.newWorkspace': '新建工作区',
        'session.workspacePrefix': '工作区'
    }
};

interface LanguageContextProps {
    language: Language;
    toggleLanguage: () => void;
    setLanguage: (language: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    // Default language is 'zh' as requested
    const [language, setLanguage] = useState<Language>('zh');

    // Optionally load from localStorage on mount
    useEffect(() => {
        const savedLang = localStorage.getItem('app_language') as Language;
        if (savedLang && (savedLang === 'en' || savedLang === 'zh')) {
            setLanguage(savedLang);
        }
    }, []);

    const toggleLanguage = useCallback(() => {
        const nextLang = language === 'zh' ? 'en' : 'zh';
        setLanguage(nextLang);
        localStorage.setItem('app_language', nextLang);
    }, [language]);

    const updateLanguage = useCallback((nextLanguage: Language) => {
        setLanguage(nextLanguage);
        localStorage.setItem('app_language', nextLanguage);
    }, []);

    const t = useCallback((key: string): string => {
        return translations[language][key] || key;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage: updateLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextProps => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
