/**
 * Resolve internal API paths (e.g. /workspace/...) to absolute backend URLs.
 *
 * Workspace links are generated by the backend and may be relative to the
 * current session. This module keeps download, preview, and relative asset
 * resolution consistent across chat messages and the global preview surface.
 */

import { API_BASE_URL, getAuthToken } from '../api/client';

const INTERNAL_PREFIXES = ['/workspace/', '/api/'];
const SESSION_RELATIVE_WORKSPACE_ROOTS = ['data', 'output', 'dashboards', 'reports'];
const WORKSPACE_FILE_ENDPOINT = '/workspace/files/';

export function isInternalApiPath(href: string | undefined): href is string {
    return !!href && INTERNAL_PREFIXES.some((prefix) => href.startsWith(prefix));
}

/** Return true for relative workspace assets emitted by the agent, e.g. data/result.csv. */
export function isWorkspaceRelativePath(href: string | undefined): href is string {
    if (!href) return false;
    const value = href.trim();
    if (!value || /^(?:[a-z][a-z0-9+.-]*:|\/|#|\?|\/\/)/i.test(value)) return false;
    const firstSegment = value.replace(/^(?:\.\/)+/, '').split(/[/?#]/)[0] || '';
    return SESSION_RELATIVE_WORKSPACE_ROOTS.includes(firstSegment);
}

function appendAuthToken(url: string): string {
    const token = getAuthToken();
    if (!token || /(?:[?&])access_token=/.test(url)) return url;
    const separator = url.includes('?') ? '&' : '?';
    return `${url}${separator}access_token=${encodeURIComponent(token)}`;
}

function toAbsoluteApiUrl(href: string): URL {
    return new URL(href, API_BASE_URL || window.location.origin);
}

function isWorkspaceFileEndpoint(pathname: string): boolean {
    return pathname.endsWith(`${WORKSPACE_FILE_ENDPOINT}download`)
        || pathname.endsWith(`${WORKSPACE_FILE_ENDPOINT}preview`);
}

function isDesktopRuntime(): boolean {
    return typeof window !== 'undefined' && Boolean(window.dataAgentRuntime);
}

function buildDesktopWorkspaceUrl(endpoint: 'download' | 'preview', path: string): string {
    const url = new URL(`data-agent://workspace${WORKSPACE_FILE_ENDPOINT}${endpoint}`);
    url.searchParams.set('path', path);
    return url.toString();
}

function workspaceFilePath(url: URL): string {
    return url.searchParams.get('path') || '';
}

function normalizePathSegments(parts: string[]): string {
    const normalized: string[] = [];
    for (const part of parts) {
        if (!part || part === '.') continue;
        if (part === '..') {
            normalized.pop();
            continue;
        }
        normalized.push(part);
    }
    return normalized.join('/');
}

function sourceWorkspacePath(sourceUrl: string | undefined): string {
    if (!sourceUrl) return '';
    try {
        return workspaceFilePath(toAbsoluteApiUrl(sourceUrl));
    } catch {
        return '';
    }
}

function resolveRelativeWorkspacePath(value: string, sourceUrl?: string, currentSessionId?: string): string {
    const sourcePath = sourceWorkspacePath(sourceUrl);
    const sourceParts = sourcePath ? sourcePath.split('/') : [];
    const sourceSession = sourceParts[0] || currentSessionId || '';
    const sourceDirectory = sourceParts.length > 1 ? sourceParts.slice(0, -1) : [];
    const assetParts = value.split('/');
    const firstAssetSegment = assetParts.find((part) => part && part !== '.');
    const basePath = firstAssetSegment && SESSION_RELATIVE_WORKSPACE_ROOTS.includes(firstAssetSegment)
        ? [sourceSession]
        : sourceDirectory;
    return normalizePathSegments([...basePath, ...assetParts]);
}

function buildWorkspaceFileUrl(endpoint: 'download' | 'preview', path: string): string {
    if (isDesktopRuntime()) return buildDesktopWorkspaceUrl(endpoint, path);
    const url = new URL(`${API_BASE_URL}/api/workspace/download`, API_BASE_URL || window.location.origin);
    url.searchParams.set('path', path);
    return appendAuthTokenWithoutDuplicate(url);
}

/** Resolve an internal relative API path to an absolute URL with auth. */
export function resolveInternalUrl(href: string | undefined, currentSessionId?: string): string {
    if (!href) return '';
    if (href.startsWith('http://') || href.startsWith('https://') || href.startsWith('data:') || href.startsWith('blob:')) {
        return href;
    }

    if (isInternalApiPath(href)) {
        const normalizedHref = normalizeWorkspaceDownloadPath(href, currentSessionId);
        if (isDesktopRuntime()) {
            try {
                const url = new URL(normalizedHref, 'http://data-agent.local');
                if (isWorkspaceFileEndpoint(url.pathname)) {
                    const endpoint = url.pathname.endsWith('/preview') ? 'preview' : 'download';
                    return buildDesktopWorkspaceUrl(endpoint, workspaceFilePath(url));
                }
            } catch {
                // Fall through to the legacy URL for non-workspace paths.
            }
        }
        return appendAuthToken(`${API_BASE_URL}${normalizedHref}`);
    }

    return href;
}

/** Resolve a workspace link to the authenticated download endpoint. */
export function resolveWorkspaceDownloadUrl(href: string | undefined, currentSessionId?: string): string {
    if (!href) return '';
    const value = href.trim();
    if (isWorkspaceRelativePath(value)) {
        const path = resolveRelativeWorkspacePath(value, undefined, currentSessionId);
        return path ? buildWorkspaceFileUrl('download', path) : value;
    }

    try {
        const url = toAbsoluteApiUrl(value);
        if (!isWorkspaceFileEndpoint(url.pathname)) {
            return resolveInternalUrl(value, currentSessionId);
        }
        const normalizedPath = normalizeWorkspacePath(workspaceFilePath(url), currentSessionId);
        if (isDesktopRuntime()) return buildDesktopWorkspaceUrl('download', normalizedPath);
        url.pathname = url.pathname.replace(/\/(?:download|preview)$/, '/download');
        url.searchParams.set('path', normalizedPath);
        return appendAuthTokenWithoutDuplicate(url);
    } catch {
        return resolveInternalUrl(value, currentSessionId);
    }
}

/** Convert a workspace download URL or relative asset to its inline preview endpoint. */
export function resolveWorkspacePreviewUrl(href: string | undefined, currentSessionId?: string): string {
    if (!href) return '';
    const value = href.trim();
    if (isWorkspaceRelativePath(value)) {
        const path = resolveRelativeWorkspacePath(value, undefined, currentSessionId);
        return path ? buildWorkspaceFileUrl('preview', path) : value;
    }

    try {
        const url = toAbsoluteApiUrl(value);
        if (!isWorkspaceFileEndpoint(url.pathname)) {
            return resolveInternalUrl(value, currentSessionId);
        }
        const normalizedPath = normalizeWorkspacePath(workspaceFilePath(url), currentSessionId);
        if (isDesktopRuntime()) return buildDesktopWorkspaceUrl('preview', normalizedPath);
        url.pathname = url.pathname.replace(/\/download$/, '/preview');
        url.searchParams.set('path', normalizedPath);
        return appendAuthTokenWithoutDuplicate(url);
    } catch {
        return resolveInternalUrl(value, currentSessionId);
    }
}

/** Resolve a relative image/link asset next to a workspace file. */
export function resolveWorkspaceAssetUrl(
    href: string | undefined,
    sourceUrl?: string,
    currentSessionId?: string,
): string {
    if (!href) return '';
    const value = href.trim();
    if (!value || value.startsWith('#') || /^(data|blob|mailto|tel|javascript):/i.test(value)) return value;
    if (/^(https?:)?\/\//i.test(value)) return value;

    if (value.startsWith('/workspace/files/download') || value.startsWith('/workspace/files/preview')) {
        return resolveWorkspacePreviewUrl(value, currentSessionId);
    }
    if (value.startsWith('/')) return resolveInternalUrl(value, currentSessionId);

    const assetPath = resolveRelativeWorkspacePath(value, sourceUrl, currentSessionId);
    const sourceSession = assetPath.split('/')[0] || '';
    if (!assetPath || !sourceSession) return value;
    return resolveWorkspacePreviewUrl(`/workspace/files/preview?path=${encodeURIComponent(assetPath)}`);
}

function normalizeWorkspacePath(path: string, currentSessionId?: string): string {
    if (!currentSessionId || !path) return path;
    const firstSegment = path.split('/')[0] || '';
    if (firstSegment === currentSessionId || !SESSION_RELATIVE_WORKSPACE_ROOTS.includes(firstSegment)) {
        return path;
    }
    return `${currentSessionId}/${path}`;
}

function normalizeWorkspaceDownloadPath(href: string, currentSessionId?: string): string {
    if (!currentSessionId || !isInternalApiPath(href)) return href;
    try {
        const url = new URL(href, 'http://data-agent.local');
        if (!isWorkspaceFileEndpoint(url.pathname)) return href;
        const path = workspaceFilePath(url);
        url.searchParams.set('path', normalizeWorkspacePath(path, currentSessionId));
        return `${url.pathname}${url.search}`;
    } catch {
        return href;
    }
}

function appendAuthTokenWithoutDuplicate(url: URL): string {
    if (!url.searchParams.has('access_token')) {
        const token = getAuthToken();
        if (token) url.searchParams.set('access_token', token);
    }
    return url.toString();
}
